package io.github.jabrena.juno.backend;

import io.github.jabrena.juno.classfile.MethodRef;
import io.github.jabrena.juno.intrinsic.Intrinsic;
import io.github.jabrena.juno.ir.BinaryOp;
import io.github.jabrena.juno.ir.Condition;
import io.github.jabrena.juno.ir.IrBasicBlock;
import io.github.jabrena.juno.ir.IrInstruction;
import io.github.jabrena.juno.ir.IrMethod;
import io.github.jabrena.juno.ir.IrProgram;
import io.github.jabrena.juno.ir.IrTerminator;
import io.github.jabrena.juno.ir.UnaryOp;
import io.github.jabrena.juno.ir.Value;
import io.github.jabrena.juno.linker.Descriptor;

import java.util.EnumSet;
import java.util.List;
import java.util.Set;

/** Emits portable Arduino C++ from Juno IR, which the Renesas core compiles to Cortex-M4 machine code. */
public final class ArduinoCppBackend {
    private static final Set<Intrinsic> LED_MATRIX_INTRINSICS = EnumSet.of(
            Intrinsic.LED_MATRIX_BEGIN, Intrinsic.LED_MATRIX_LOAD_FRAME, Intrinsic.LED_MATRIX_CLEAR);
    private static final Set<Intrinsic> MOUSE_INTRINSICS = EnumSet.of(Intrinsic.MOUSE_BEGIN, Intrinsic.MOUSE_MOVE);

    public String generate(IrProgram program) {
        boolean usesLedMatrix = usesAnyIntrinsic(program, LED_MATRIX_INTRINSICS);
        boolean usesMouse = usesAnyIntrinsic(program, MOUSE_INTRINSICS);
        StringBuilder output = new StringBuilder();
        output.append("// Generated by Juno. Do not edit.\n")
                .append("// Closed-world entry point: ").append(program.entryPoint().displayName()).append("\n")
                .append("#include <Arduino.h>\n")
                .append("#include <stdint.h>\n");
        if (usesLedMatrix) {
            output.append("#include \"Arduino_LED_Matrix.h\"\n");
        }
        if (usesMouse) {
            output.append("#include <Mouse.h>\n");
        }
        output.append('\n').append(runtimeHelpers());
        if (usesLedMatrix) {
            output.append(ledMatrixHelpers());
        }

        for (IrMethod method : program.methods()) {
            output.append(prototype(method.reference())).append(";\n");
        }
        output.append('\n');
        for (IrMethod method : program.methods()) {
            emitMethod(output, method);
        }

        Descriptor entryDescriptor = Descriptor.parse(program.entryPoint().descriptor());
        output.append("void setup() {\n  ")
                .append(CppNames.method(program.entryPoint())).append('(');
        if (!entryDescriptor.parameters().isEmpty()) {
            output.append('0'); // closed-world programs have no command-line arguments
        }
        output.append(");\n}\n\nvoid loop() {\n}\n");
        return output.toString();
    }

    private boolean usesAnyIntrinsic(IrProgram program, Set<Intrinsic> intrinsics) {
        for (IrMethod method : program.methods()) {
            for (IrBasicBlock block : method.blocks()) {
                for (IrInstruction instruction : block.instructions()) {
                    if (instruction instanceof IrInstruction.IntrinsicCall call && intrinsics.contains(call.intrinsic())) {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    private void emitMethod(StringBuilder output, IrMethod method) {
        Descriptor descriptor = Descriptor.parse(method.reference().descriptor());
        output.append(prototype(method.reference())).append(" {\n")
                .append("  int32_t locals[").append(Math.max(1, method.maxLocals())).append("] = {};\n");
        for (int index = 0; index < descriptor.parameters().size(); index++) {
            output.append("  locals[").append(index).append("] = arg").append(index).append(";\n");
        }
        if (method.valueCount() > 0) {
            // Declared without initializers, and up front: a goto into a later block must not jump
            // over an initialized variable's declaration, so every value is assigned, never declared, below.
            output.append("  int32_t ");
            for (int index = 0; index < method.valueCount(); index++) {
                if (index > 0) {
                    output.append(", ");
                }
                output.append('v').append(index);
            }
            output.append(";\n");
        }
        for (IrBasicBlock block : method.blocks()) {
            emitBlock(output, block);
        }
        if (descriptor.returnsVoid()) {
            output.append("  return;\n");
        } else {
            output.append("  juno_panic();\n  return 0;\n");
        }
        output.append("}\n\n");
    }

    private void emitBlock(StringBuilder output, IrBasicBlock block) {
        output.append("juno_pc_").append(block.start()).append(":\n");
        List<IrInstruction> instructions = block.instructions();
        int limit = instructions.size();
        IrInstruction.Compare foldedCompare = null;
        if (block.terminator() instanceof IrTerminator.Branch branch
                && limit > 0
                && instructions.get(limit - 1) instanceof IrInstruction.Compare compare
                && compare.target().equals(branch.condition())) {
            foldedCompare = compare;
            limit -= 1;
        }
        for (int index = 0; index < limit; index++) {
            emitInstruction(output, instructions.get(index));
        }
        emitTerminator(output, block.terminator(), foldedCompare);
    }

    private void emitInstruction(StringBuilder output, IrInstruction instruction) {
        switch (instruction) {
            case IrInstruction.Const constant ->
                    assign(output, constant.target(), Integer.toString(constant.value()));
            case IrInstruction.LoadLocal load ->
                    assign(output, load.target(), "locals[" + load.local() + "]");
            case IrInstruction.StoreLocal store ->
                    output.append("  locals[").append(store.local()).append("] = ").append(ref(store.value())).append(";\n");
            case IrInstruction.Binary binary -> assign(output, binary.target(),
                    helperFor(binary.operation()) + "(" + ref(binary.left()) + ", " + ref(binary.right()) + ")");
            case IrInstruction.Unary unary -> assign(output, unary.target(), unaryExpression(unary));
            case IrInstruction.Compare compare -> assign(output, compare.target(),
                    "(" + ref(compare.left()) + " " + operatorFor(compare.condition()) + " " + ref(compare.right()) + ") ? 1 : 0");
            case IrInstruction.Call call -> emitUserCall(output, call);
            case IrInstruction.IntrinsicCall call -> emitIntrinsicCall(output, call);
        }
    }

    private void emitTerminator(StringBuilder output, IrTerminator terminator, IrInstruction.Compare foldedCompare) {
        switch (terminator) {
            case IrTerminator.Jump jump -> output.append("  goto juno_pc_").append(jump.target()).append(";\n");
            case IrTerminator.Branch branch -> {
                String condition = foldedCompare != null
                        ? ref(foldedCompare.left()) + " " + operatorFor(foldedCompare.condition()) + " " + ref(foldedCompare.right())
                        : ref(branch.condition()) + " != 0";
                output.append("  if (").append(condition).append(") goto juno_pc_").append(branch.trueTarget()).append(";\n")
                        .append("  goto juno_pc_").append(branch.falseTarget()).append(";\n");
            }
            case IrTerminator.Return returned -> {
                if (returned.value().isPresent()) {
                    output.append("  return ").append(ref(returned.value().get())).append(";\n");
                } else {
                    output.append("  return;\n");
                }
            }
        }
    }

    private void emitUserCall(StringBuilder output, IrInstruction.Call call) {
        output.append("  ");
        if (call.target().isPresent()) {
            output.append(ref(call.target().get())).append(" = ");
        }
        output.append(CppNames.method(call.method())).append('(');
        List<Value> arguments = call.arguments();
        for (int index = 0; index < arguments.size(); index++) {
            if (index > 0) {
                output.append(", ");
            }
            output.append(ref(arguments.get(index)));
        }
        output.append(");\n");
    }

    private void emitIntrinsicCall(StringBuilder output, IrInstruction.IntrinsicCall call) {
        output.append("  {\n");
        List<Value> arguments = call.arguments();
        for (int index = 0; index < arguments.size(); index++) {
            output.append("    int32_t call_arg").append(index).append(" = ").append(ref(arguments.get(index))).append(";\n");
        }
        if (call.receiver().isPresent()) {
            output.append("    int32_t call_receiver = ").append(ref(call.receiver().get())).append(";\n");
        }
        output.append("    ");
        if (call.target().isPresent()) {
            output.append(ref(call.target().get())).append(" = ");
        }
        output.append(intrinsicExpression(call.intrinsic())).append(";\n  }\n");
    }

    private String intrinsicExpression(Intrinsic intrinsic) {
        return switch (intrinsic) {
            case GPIO_PIN_MODE -> "pinMode(call_arg0, call_arg1)";
            case GPIO_DIGITAL_WRITE -> "digitalWrite(call_arg0, call_arg1 ? HIGH : LOW)";
            case GPIO_DIGITAL_READ -> "static_cast<int32_t>(digitalRead(call_arg0) == HIGH)";
            case GPIO_ANALOG_READ -> "static_cast<int32_t>(analogRead(call_arg0))";
            case GPIO_ANALOG_WRITE -> "analogWrite(call_arg0, call_arg1)";
            case GPIO_TOGGLE -> "digitalWrite(call_arg0, digitalRead(call_arg0) == HIGH ? LOW : HIGH)";
            case DELAY_MILLIS -> "delay(static_cast<unsigned long>(call_arg0))";
            case DELAY_MICROS -> "delayMicroseconds(static_cast<unsigned int>(call_arg0))";
            case CLOCK_MILLIS -> "static_cast<int32_t>(millis())";
            case CLOCK_MICROS -> "static_cast<int32_t>(micros())";
            case DIGITAL_OUTPUT_OF -> "juno_digital_output_of(call_arg0)";
            case DIGITAL_OUTPUT_HIGH -> "digitalWrite(call_receiver, HIGH)";
            case DIGITAL_OUTPUT_LOW -> "digitalWrite(call_receiver, LOW)";
            case DIGITAL_OUTPUT_TOGGLE -> "digitalWrite(call_receiver, digitalRead(call_receiver) == HIGH ? LOW : HIGH)";
            case DIGITAL_OUTPUT_IS_HIGH -> "static_cast<int32_t>(digitalRead(call_receiver) == HIGH)";
            case LED_MATRIX_BEGIN -> "juno_led_matrix_begin()";
            case LED_MATRIX_LOAD_FRAME -> "juno_led_matrix_load_frame(call_arg0, call_arg1, call_arg2)";
            case LED_MATRIX_CLEAR -> "juno_led_matrix_clear()";
            case SERIAL_BEGIN -> "Serial.begin(static_cast<unsigned long>(call_arg0))";
            case SERIAL_PRINT -> "Serial.print(call_arg0)";
            case SERIAL_PRINTLN -> "Serial.println(call_arg0)";
            case MOUSE_BEGIN -> "Mouse.begin()";
            case MOUSE_MOVE -> "Mouse.move(static_cast<signed char>(call_arg0), static_cast<signed char>(call_arg1))";
        };
    }

    private String unaryExpression(IrInstruction.Unary unary) {
        String operand = ref(unary.value());
        return switch (unary.operation()) {
            case NEGATE -> "juno_ineg(" + operand + ")";
            case TO_BYTE -> "juno_i2b(" + operand + ")";
            case TO_CHAR -> "static_cast<uint16_t>(" + operand + ")";
            case TO_SHORT -> "juno_i2s(" + operand + ")";
        };
    }

    private String helperFor(BinaryOp operation) {
        return switch (operation) {
            case ADD -> "juno_iadd";
            case SUBTRACT -> "juno_isub";
            case MULTIPLY -> "juno_imul";
            case DIVIDE -> "juno_idiv";
            case REMAINDER -> "juno_irem";
            case SHIFT_LEFT -> "juno_ishl";
            case SHIFT_RIGHT -> "juno_ishr";
            case UNSIGNED_SHIFT_RIGHT -> "juno_iushr";
            case AND -> "juno_iand";
            case OR -> "juno_ior";
            case XOR -> "juno_ixor";
        };
    }

    private String operatorFor(Condition condition) {
        return switch (condition) {
            case EQUAL -> "==";
            case NOT_EQUAL -> "!=";
            case LESS_THAN -> "<";
            case GREATER_EQUAL -> ">=";
            case GREATER_THAN -> ">";
            case LESS_EQUAL -> "<=";
        };
    }

    private void assign(StringBuilder output, Value target, String expression) {
        output.append("  ").append(ref(target)).append(" = ").append(expression).append(";\n");
    }

    private String ref(Value value) {
        return "v" + value.id();
    }

    private String prototype(MethodRef method) {
        Descriptor descriptor = Descriptor.parse(method.descriptor());
        String returnType = descriptor.returnsVoid() ? "void" : "int32_t";
        StringBuilder result = new StringBuilder("static ").append(returnType).append(' ')
                .append(CppNames.method(method)).append('(');
        for (int i = 0; i < descriptor.parameters().size(); i++) {
            if (i > 0) {
                result.append(", ");
            }
            result.append("int32_t arg").append(i);
        }
        return result.append(')').toString();
    }

    private String runtimeHelpers() {
        return """
                [[noreturn]] static void juno_panic() {
                  noInterrupts();
                  for (;;) {}
                }

                static int32_t juno_iadd(int32_t a, int32_t b) {
                  return static_cast<int32_t>(static_cast<uint32_t>(a) + static_cast<uint32_t>(b));
                }
                static int32_t juno_isub(int32_t a, int32_t b) {
                  return static_cast<int32_t>(static_cast<uint32_t>(a) - static_cast<uint32_t>(b));
                }
                static int32_t juno_imul(int32_t a, int32_t b) {
                  return static_cast<int32_t>(static_cast<uint32_t>(a) * static_cast<uint32_t>(b));
                }
                static int32_t juno_idiv(int32_t a, int32_t b) {
                  if (b == 0) juno_panic();
                  if (a == INT32_MIN && b == -1) return INT32_MIN;
                  return a / b;
                }
                static int32_t juno_irem(int32_t a, int32_t b) {
                  if (b == 0) juno_panic();
                  if (a == INT32_MIN && b == -1) return 0;
                  return a % b;
                }
                static int32_t juno_ineg(int32_t value) {
                  return static_cast<int32_t>(0u - static_cast<uint32_t>(value));
                }
                static int32_t juno_ishl(int32_t a, int32_t b) {
                  return static_cast<int32_t>(static_cast<uint32_t>(a) << (b & 31));
                }
                static int32_t juno_ishr(int32_t a, int32_t b) {
                  uint32_t shift = static_cast<uint32_t>(b) & 31u;
                  uint32_t value = static_cast<uint32_t>(a);
                  if (shift == 0 || a >= 0) return static_cast<int32_t>(value >> shift);
                  return static_cast<int32_t>((value >> shift) | (~0u << (32u - shift)));
                }
                static int32_t juno_iushr(int32_t a, int32_t b) {
                  return static_cast<int32_t>(static_cast<uint32_t>(a) >> (b & 31));
                }
                static int32_t juno_iand(int32_t a, int32_t b) { return a & b; }
                static int32_t juno_ior(int32_t a, int32_t b) { return a | b; }
                static int32_t juno_ixor(int32_t a, int32_t b) { return a ^ b; }
                static int32_t juno_i2b(int32_t value) {
                  uint32_t narrowed = static_cast<uint32_t>(value) & 0xffu;
                  return static_cast<int32_t>(narrowed >= 0x80u ? narrowed | 0xffffff00u : narrowed);
                }
                static int32_t juno_i2s(int32_t value) {
                  uint32_t narrowed = static_cast<uint32_t>(value) & 0xffffu;
                  return static_cast<int32_t>(narrowed >= 0x8000u ? narrowed | 0xffff0000u : narrowed);
                }
                static int32_t juno_digital_output_of(int32_t pin) {
                  pinMode(pin, OUTPUT);
                  return pin;
                }

                """;
    }

    private String ledMatrixHelpers() {
        return """
                ArduinoLEDMatrix juno_led_matrix;
                static void juno_led_matrix_begin() {
                  juno_led_matrix.begin();
                }
                static void juno_led_matrix_load_frame(int32_t word0, int32_t word1, int32_t word2) {
                  const uint32_t frame[3] = {
                    static_cast<uint32_t>(word0),
                    static_cast<uint32_t>(word1),
                    static_cast<uint32_t>(word2)
                  };
                  juno_led_matrix.loadFrame(frame);
                }
                static void juno_led_matrix_clear() {
                  const uint32_t frame[3] = {0, 0, 0};
                  juno_led_matrix.loadFrame(frame);
                }

                """;
    }
}
