package io.github.jabrena.juno.backend;

import io.github.jabrena.juno.RuntimeLimits;
import io.github.jabrena.juno.classfile.FieldRef;
import io.github.jabrena.juno.classfile.MethodRef;
import io.github.jabrena.juno.intrinsic.Intrinsic;
import io.github.jabrena.juno.ir.ArrayDeclaration;
import io.github.jabrena.juno.ir.ArrayElementType;
import io.github.jabrena.juno.ir.BinaryOp;
import io.github.jabrena.juno.ir.Condition;
import io.github.jabrena.juno.ir.FloatBinaryOp;
import io.github.jabrena.juno.ir.IrBasicBlock;
import io.github.jabrena.juno.ir.IrInstruction;
import io.github.jabrena.juno.ir.IrMethod;
import io.github.jabrena.juno.ir.IrProgram;
import io.github.jabrena.juno.ir.IrTerminator;
import io.github.jabrena.juno.ir.JunoType;
import io.github.jabrena.juno.ir.UnaryOp;
import io.github.jabrena.juno.ir.Value;
import io.github.jabrena.juno.linker.Descriptor;

import java.util.EnumSet;
import java.util.ArrayList;
import java.util.Map;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.TreeMap;

/** Emits portable Arduino C++ from Juno IR, which the Renesas core compiles to Cortex-M4 machine code. */
public final class ArduinoCppBackend {
    private static final Set<Intrinsic> LED_MATRIX_INTRINSICS = EnumSet.of(
            Intrinsic.LED_MATRIX_BEGIN, Intrinsic.LED_MATRIX_LOAD_FRAME, Intrinsic.LED_MATRIX_CLEAR);
    private static final Set<Intrinsic> MOUSE_INTRINSICS = EnumSet.of(Intrinsic.MOUSE_BEGIN, Intrinsic.MOUSE_MOVE);

    public String generate(IrProgram program) {
        boolean usesLedMatrix = usesAnyIntrinsic(program, LED_MATRIX_INTRINSICS);
        boolean usesMouse = usesAnyIntrinsic(program, MOUSE_INTRINSICS);
        boolean usesFloatingPoint = program.methods().stream().anyMatch(this::usesFloatingPoint);
        StringBuilder output = new StringBuilder();
        output.append("// Generated by Juno. Do not edit.\n")
                .append("// Closed-world entry point: ").append(program.entryPoint().displayName()).append("\n")
                .append("#include <Arduino.h>\n")
                .append("#include <stdint.h>\n");
        if (usesFloatingPoint) {
            output.append("#include <math.h>\n");
        }
        if (usesLedMatrix) {
            output.append("#include \"Arduino_LED_Matrix.h\"\n");
        }
        if (usesMouse) {
            output.append("#include <Mouse.h>\n");
        }
        output.append('\n').append(runtimeHelpers());
        if (usesFloatingPoint) {
            output.append(floatingPointHelpers());
        }
        if (usesLedMatrix) {
            output.append(ledMatrixHelpers());
        }

        emitObjectLayouts(output, program);

        List<FieldRef> staticFields = usedStaticFields(program);
        for (FieldRef field : staticFields) {
            output.append("static ").append(cppScalarType(field.descriptor())).append(' ')
                    .append(CppNames.field(field)).append(" = {};\n");
        }
        if (!staticFields.isEmpty()) {
            output.append('\n');
        }

        for (IrMethod method : program.methods()) {
            output.append(prototype(method)).append(";\n");
        }
        output.append('\n');
        for (IrMethod method : program.methods()) {
            emitMethod(output, method);
        }

        Descriptor entryDescriptor = Descriptor.parse(program.entryPoint().descriptor());
        output.append("void setup() {\n");
        for (IrMethod method : program.methods()) {
            if (method.reference().name().equals("<clinit>")) {
                output.append("  ").append(CppNames.method(method.reference())).append("();\n");
            }
        }
        output.append("  ").append(CppNames.method(program.entryPoint())).append('(');
        if (!entryDescriptor.parameters().isEmpty()) {
            output.append('0'); // closed-world programs have no command-line arguments
        }
        output.append(");\n}\n\nvoid loop() {\n}\n");
        return output.toString();
    }

    private boolean usesAnyIntrinsic(IrProgram program, Set<Intrinsic> intrinsics) {
        for (IrMethod method : program.methods()) {
            for (IrBasicBlock block : method.blocks()) {
                for (IrInstruction instruction : block.instructions()) {
                    if (instruction instanceof IrInstruction.IntrinsicCall call && intrinsics.contains(call.intrinsic())) {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    private List<FieldRef> usedStaticFields(IrProgram program) {
        TreeMap<String, FieldRef> fields = new TreeMap<>();
        for (IrMethod method : program.methods()) {
            for (IrBasicBlock block : method.blocks()) {
                for (IrInstruction instruction : block.instructions()) {
                    FieldRef field = switch (instruction) {
                        case IrInstruction.LoadStatic load -> load.field();
                        case IrInstruction.StoreStatic store -> store.field();
                        default -> null;
                    };
                    if (field != null) {
                        fields.put(field.displayName(), field);
                    }
                }
            }
        }
        return List.copyOf(fields.values());
    }

    private void emitObjectLayouts(StringBuilder output, IrProgram program) {
        TreeMap<String, TreeMap<String, FieldRef>> layouts = new TreeMap<>();
        for (IrMethod method : program.methods()) {
            for (IrBasicBlock block : method.blocks()) {
                for (IrInstruction instruction : block.instructions()) {
                    if (instruction instanceof IrInstruction.NewObject object) {
                        layouts.computeIfAbsent(object.className(), ignored -> new TreeMap<>());
                    } else if (instruction instanceof IrInstruction.LoadField load) {
                        layouts.computeIfAbsent(load.field().owner(), ignored -> new TreeMap<>())
                                .put(load.field().displayName(), load.field());
                    } else if (instruction instanceof IrInstruction.StoreField store) {
                        layouts.computeIfAbsent(store.field().owner(), ignored -> new TreeMap<>())
                                .put(store.field().displayName(), store.field());
                    }
                }
            }
        }
        for (Map.Entry<String, TreeMap<String, FieldRef>> layout : layouts.entrySet()) {
            output.append("struct ").append(CppNames.objectType(layout.getKey())).append(" {\n");
            if (layout.getValue().isEmpty()) {
                output.append("  uint8_t unused;\n");
            } else {
                for (FieldRef field : layout.getValue().values()) {
                    output.append("  ").append(cppScalarType(field.descriptor())).append(' ')
                            .append(CppNames.instanceField(field)).append(";\n");
                }
            }
            output.append("};\n");
        }
        if (!layouts.isEmpty()) {
            output.append('\n');
        }
    }

    private boolean usesFloatingPoint(IrMethod method) {
        Descriptor descriptor = Descriptor.parse(method.reference().descriptor());
        return Descriptor.isFloat(descriptor.returnType()) || Descriptor.isDouble(descriptor.returnType())
                || descriptor.parameters().stream().anyMatch(
                        type -> Descriptor.isFloat(type) || Descriptor.isDouble(type))
                || method.values().stream().anyMatch(
                        value -> value.type() == JunoType.FLOAT32 || value.type() == JunoType.FLOAT64);
    }

    private boolean usesTypedValues(IrMethod method) {
        return method.values().stream().anyMatch(value -> value.type() != JunoType.INT32)
                || Descriptor.parse(method.reference().descriptor()).parameters().stream()
                        .anyMatch(type -> Descriptor.isLong(type) || Descriptor.isFloat(type)
                                || Descriptor.isDouble(type));
    }

    private void emitMethod(StringBuilder output, IrMethod method) {
        Descriptor descriptor = Descriptor.parse(method.reference().descriptor());
        boolean typedLocals = usesTypedValues(method);
        output.append(prototype(method)).append(" {\n");
        if (typedLocals) {
            output.append("  union JunoSlot { int32_t i32; int64_t i64; float f32; double f64; };\n")
                    .append("  JunoSlot locals[").append(Math.max(1, method.maxLocals())).append("] = {};\n");
        } else {
            output.append("  int32_t locals[").append(Math.max(1, method.maxLocals())).append("] = {};\n");
        }
        List<String> parameterTypes = descriptor.parameters();
        int localSlot = 0;
        if (!method.isStatic()) {
            output.append("  ").append(localRef(0, JunoType.INT32, typedLocals)).append(" = arg_receiver;\n");
            localSlot = 1;
        }
        for (int index = 0; index < parameterTypes.size(); index++) {
            String parameterType = parameterTypes.get(index);
            if (Descriptor.isLong(parameterType)) {
                output.append("  ").append(localRef(localSlot, JunoType.INT32, typedLocals)).append(" = ")
                        .append(splitLow("arg" + index)).append(";\n")
                        .append("  ").append(localRef(localSlot + 1, JunoType.INT32, typedLocals)).append(" = ")
                        .append(splitHigh("arg" + index)).append(";\n");
                localSlot += 2;
                continue;
            }
            JunoType junoType = Descriptor.isDouble(parameterType)
                    ? JunoType.FLOAT64
                    : Descriptor.isFloat(parameterType) ? JunoType.FLOAT32 : JunoType.INT32;
            output.append("  ").append(localRef(localSlot, junoType, typedLocals)).append(" = ");
            if (Descriptor.isArrayType(parameterType)) {
                output.append(handleOf("arg" + index));
            } else {
                output.append("arg").append(index);
            }
            output.append(";\n");
            localSlot += Descriptor.jvmSlots(parameterType);
        }
        emitValueDeclarations(output, method.values());
        emitConstantArrayDeclarations(output, method);
        Optional<ArrayElementType> returnArrayType = arrayElementTypeOf(descriptor.returnType());
        for (IrBasicBlock block : method.blocks()) {
            emitBlock(output, block, returnArrayType, typedLocals);
        }
        if (descriptor.returnsVoid()) {
            output.append("  return;\n");
        } else if (Descriptor.isFloat(descriptor.returnType())) {
            output.append("  juno_panic();\n  return 0.0f;\n");
        } else if (Descriptor.isDouble(descriptor.returnType())) {
            output.append("  juno_panic();\n  return 0.0;\n");
        } else {
            output.append("  juno_panic();\n  return 0;\n");
        }
        output.append("}\n\n");
    }

    private void emitConstantArrayDeclarations(StringBuilder output, IrMethod method) {
        for (IrBasicBlock block : method.blocks()) {
            for (IrInstruction instruction : block.instructions()) {
                if (instruction instanceof IrInstruction.IntArrayConst array) {
                    output.append("  static int32_t juno_const_array_").append(array.target().id()).append("[] = {");
                    for (int index = 0; index < array.values().size(); index++) {
                        if (index > 0) {
                            output.append(", ");
                        }
                        output.append(array.values().get(index));
                    }
                    output.append("};\n");
                }
            }
        }
    }

    private void emitValueDeclarations(StringBuilder output, List<Value> values) {
        // Declared without initializers, and up front: a goto into a later block must not jump
        // over an initialized variable's declaration, so every value is assigned, never declared, below.
        for (JunoType type : JunoType.values()) {
            List<Value> typedValues = values.stream().filter(value -> value.type() == type).toList();
            if (typedValues.isEmpty()) {
                continue;
            }
            output.append("  ").append(cppType(type)).append(' ');
            for (int index = 0; index < typedValues.size(); index++) {
                if (index > 0) {
                    output.append(", ");
                }
                output.append(ref(typedValues.get(index)));
            }
            output.append(";\n");
        }
    }

    private String cppType(JunoType type) {
        return switch (type) {
            case INT32 -> "int32_t";
            case INT64 -> "int64_t";
            case FLOAT32 -> "float";
            case FLOAT64 -> "double";
        };
    }

    private String cppScalarType(String descriptor) {
        if (Descriptor.isDouble(descriptor)) {
            return "double";
        }
        if (Descriptor.isLong(descriptor)) {
            return "int64_t";
        }
        return Descriptor.isFloat(descriptor) ? "float" : "int32_t";
    }

    private void emitBlock(StringBuilder output, IrBasicBlock block, Optional<ArrayElementType> returnArrayType,
                           boolean typedLocals) {
        output.append("juno_pc_").append(block.start()).append(":\n");
        List<IrInstruction> instructions = block.instructions();
        int limit = instructions.size();
        IrInstruction.Compare foldedCompare = null;
        if (block.terminator() instanceof IrTerminator.Branch branch
                && limit > 0
                && instructions.get(limit - 1) instanceof IrInstruction.Compare compare
                && compare.target().equals(branch.condition())) {
            foldedCompare = compare;
            limit -= 1;
        }
        for (int index = 0; index < limit; index++) {
            emitInstruction(output, instructions.get(index), typedLocals);
        }
        emitTerminator(output, block.start(), block.terminator(), foldedCompare, returnArrayType);
    }

    private void emitInstruction(StringBuilder output, IrInstruction instruction, boolean typedLocals) {
        switch (instruction) {
            case IrInstruction.Const constant ->
                    assign(output, constant.target(), Integer.toString(constant.value()));
            case IrInstruction.FloatConst constant ->
                    assign(output, constant.target(), floatLiteral(constant.value()));
            case IrInstruction.DoubleConst constant ->
                    assign(output, constant.target(), doubleLiteral(constant.value()));
            case IrInstruction.LoadLocal load ->
                    assign(output, load.target(), localRef(load.local(), load.target().type(), typedLocals));
            case IrInstruction.StoreLocal store ->
                    output.append("  ").append(localRef(store.local(), store.value().type(), typedLocals))
                            .append(" = ").append(ref(store.value())).append(";\n");
            case IrInstruction.LoadStatic load -> assign(output, load.target(), CppNames.field(load.field()));
            case IrInstruction.StoreStatic store -> output.append("  ").append(CppNames.field(store.field()))
                    .append(" = ").append(ref(store.value())).append(";\n");
            case IrInstruction.NewObject object -> assign(output, object.target(),
                    handleOf(allocationExpression(CppNames.objectType(object.className()), "1")));
            case IrInstruction.LoadField load -> assign(output, load.target(), fieldExpression(load.field(), load.receiver()));
            case IrInstruction.StoreField store -> output.append("  ")
                    .append(fieldExpression(store.field(), store.receiver())).append(" = ")
                    .append(ref(store.value())).append(";\n");
            case IrInstruction.IntArrayConst array -> assign(output, array.target(),
                    handleOf("juno_const_array_" + array.target().id()));
            case IrInstruction.NewMultiArray array -> emitMultiArray(output, array);
            case IrInstruction.Panic ignored -> output.append("  juno_panic();\n");
            case IrInstruction.Binary binary -> assign(output, binary.target(),
                    helperFor(binary.operation()) + "(" + ref(binary.left()) + ", " + ref(binary.right()) + ")");
            case IrInstruction.Unary unary -> assign(output, unary.target(), unaryExpression(unary));
            case IrInstruction.Compare compare -> assign(output, compare.target(),
                    "(" + ref(compare.left()) + " " + operatorFor(compare.condition()) + " " + ref(compare.right()) + ") ? 1 : 0");
            case IrInstruction.Call call -> emitUserCall(output, call);
            case IrInstruction.IntrinsicCall call -> emitIntrinsicCall(output, call);
            case IrInstruction.NewArray newArray -> assign(output, newArray.target(),
                    handleOf(allocationExpression(cppType(newArray.elementType()), Integer.toString(newArray.length()))));
            case IrInstruction.ArrayLoad load -> assign(output, load.target(),
                    "reinterpret_cast<" + cppType(load.elementType()) + "*>(" + ref(load.array()) + ")[" + ref(load.index()) + "]");
            case IrInstruction.ArrayStore store -> output.append("  reinterpret_cast<").append(cppType(store.elementType()))
                    .append("*>(").append(ref(store.array())).append(")[").append(ref(store.index())).append("] = ")
                    .append(ref(store.value())).append(";\n");
            case IrInstruction.BoundsCheck check -> output.append("  if (").append(ref(check.index()))
                    .append(" < 0 || ").append(ref(check.index())).append(" >= ").append(check.length())
                    .append(") juno_panic();\n");
            case IrInstruction.LongConst constant -> {
                long value = constant.value();
                assign(output, constant.targetLow(), Integer.toString((int) value));
                assign(output, constant.targetHigh(), Integer.toString((int) (value >>> 32)));
            }
            case IrInstruction.LongBinary binary -> {
                output.append("  {\n")
                        .append("    int64_t juno_l = ").append(combineLong(binary.leftLow(), binary.leftHigh())).append(";\n")
                        .append("    int64_t juno_r = ").append(combineLong(binary.rightLow(), binary.rightHigh())).append(";\n")
                        .append("    int64_t juno_res = ").append(longHelperFor(binary.operation())).append("(juno_l, juno_r);\n")
                        .append("    ").append(ref(binary.targetLow())).append(" = ").append(splitLow("juno_res")).append(";\n")
                        .append("    ").append(ref(binary.targetHigh())).append(" = ").append(splitHigh("juno_res")).append(";\n")
                        .append("  }\n");
            }
            case IrInstruction.LongShift shift -> {
                output.append("  {\n")
                        .append("    int64_t juno_l = ").append(combineLong(shift.valueLow(), shift.valueHigh())).append(";\n")
                        .append("    int64_t juno_res = ").append(longShiftHelperFor(shift.operation()))
                        .append("(juno_l, ").append(ref(shift.shiftAmount())).append(");\n")
                        .append("    ").append(ref(shift.targetLow())).append(" = ").append(splitLow("juno_res")).append(";\n")
                        .append("    ").append(ref(shift.targetHigh())).append(" = ").append(splitHigh("juno_res")).append(";\n")
                        .append("  }\n");
            }
            case IrInstruction.LongNegate negate -> {
                output.append("  {\n")
                        .append("    int64_t juno_res = juno_lneg(").append(combineLong(negate.valueLow(), negate.valueHigh())).append(");\n")
                        .append("    ").append(ref(negate.targetLow())).append(" = ").append(splitLow("juno_res")).append(";\n")
                        .append("    ").append(ref(negate.targetHigh())).append(" = ").append(splitHigh("juno_res")).append(";\n")
                        .append("  }\n");
            }
            case IrInstruction.LongCompare compare -> {
                output.append("  {\n")
                        .append("    int64_t juno_l = ").append(combineLong(compare.leftLow(), compare.leftHigh())).append(";\n")
                        .append("    int64_t juno_r = ").append(combineLong(compare.rightLow(), compare.rightHigh())).append(";\n")
                        .append("    ").append(ref(compare.target())).append(" = (juno_l > juno_r) - (juno_l < juno_r);\n")
                        .append("  }\n");
            }
            case IrInstruction.IntToLong widen -> {
                // Sign-extending an int32 to int64 needs no 64-bit arithmetic: the low half is the value
                // unchanged, and the high half is all-0s or all-1s depending on its sign, i.e. value >> 31.
                assign(output, widen.targetLow(), ref(widen.value()));
                assign(output, widen.targetHigh(), ref(widen.value()) + " >> 31");
            }
            case IrInstruction.LongToInt narrow -> assign(output, narrow.target(), ref(narrow.valueLow()));
            case IrInstruction.FloatBinary binary -> assign(output, binary.target(),
                    floatBinaryExpression(binary.operation(), binary.left(), binary.right()));
            case IrInstruction.FloatNegate negate -> assign(output, negate.target(), "-" + ref(negate.value()));
            case IrInstruction.FloatCompare compare -> assign(output, compare.target(),
                    "(isnan(" + ref(compare.left()) + ") || isnan(" + ref(compare.right()) + ")) ? "
                            + compare.nanResult() + " : ((" + ref(compare.left()) + " > " + ref(compare.right())
                            + ") - (" + ref(compare.left()) + " < " + ref(compare.right()) + "))");
            case IrInstruction.IntToFloat conversion -> assign(output, conversion.target(),
                    "static_cast<float>(" + ref(conversion.value()) + ")");
            case IrInstruction.FloatToInt conversion -> assign(output, conversion.target(),
                    "juno_f2i(" + ref(conversion.value()) + ")");
            case IrInstruction.DoubleBinary binary -> assign(output, binary.target(),
                    doubleBinaryExpression(binary.operation(), binary.left(), binary.right()));
            case IrInstruction.DoubleNegate negate -> assign(output, negate.target(), "-" + ref(negate.value()));
            case IrInstruction.DoubleCompare compare -> assign(output, compare.target(),
                    "(isnan(" + ref(compare.left()) + ") || isnan(" + ref(compare.right()) + ")) ? "
                            + compare.nanResult() + " : ((" + ref(compare.left()) + " > " + ref(compare.right())
                            + ") - (" + ref(compare.left()) + " < " + ref(compare.right()) + "))");
            case IrInstruction.IntToDouble conversion -> assign(output, conversion.target(),
                    "static_cast<double>(" + ref(conversion.value()) + ")");
            case IrInstruction.DoubleToInt conversion -> assign(output, conversion.target(),
                    "juno_d2i(" + ref(conversion.value()) + ")");
            case IrInstruction.FloatToDouble conversion -> assign(output, conversion.target(),
                    "static_cast<double>(" + ref(conversion.value()) + ")");
            case IrInstruction.DoubleToFloat conversion -> assign(output, conversion.target(),
                    "static_cast<float>(" + ref(conversion.value()) + ")");
            case IrInstruction.LongToDouble conversion -> assign(output, conversion.target(),
                    "static_cast<double>(" + combineLong(conversion.valueLow(), conversion.valueHigh()) + ")");
            case IrInstruction.DoubleToLong conversion -> {
                output.append("  {\n")
                        .append("    int64_t juno_res = juno_d2l(").append(ref(conversion.value())).append(");\n")
                        .append("    ").append(ref(conversion.targetLow())).append(" = ")
                        .append(splitLow("juno_res")).append(";\n")
                        .append("    ").append(ref(conversion.targetHigh())).append(" = ")
                        .append(splitHigh("juno_res")).append(";\n")
                        .append("  }\n");
            }
            case IrInstruction.PackLong packed -> assign(output, packed.target(),
                    combineLong(packed.valueLow(), packed.valueHigh()));
            case IrInstruction.UnpackLong unpacked -> {
                assign(output, unpacked.targetLow(), splitLow(ref(unpacked.value())));
                assign(output, unpacked.targetHigh(), splitHigh(ref(unpacked.value())));
            }
            case IrInstruction.LongToFloat conversion -> assign(output, conversion.target(),
                    "static_cast<float>(" + combineLong(conversion.valueLow(), conversion.valueHigh()) + ")");
            case IrInstruction.FloatToLong conversion -> {
                output.append("  {\n")
                        .append("    int64_t juno_res = juno_f2l(").append(ref(conversion.value())).append(");\n")
                        .append("    ").append(ref(conversion.targetLow())).append(" = ")
                        .append(splitLow("juno_res")).append(";\n")
                        .append("    ").append(ref(conversion.targetHigh())).append(" = ")
                        .append(splitHigh("juno_res")).append(";\n")
                        .append("  }\n");
            }
        }
    }

    private String fieldExpression(FieldRef field, Value receiver) {
        return "reinterpret_cast<" + CppNames.objectType(field.owner()) + "*>(" + ref(receiver) + ")->"
                + CppNames.instanceField(field);
    }

    private void emitMultiArray(StringBuilder output, IrInstruction.NewMultiArray array) {
        assign(output, array.target(), handleOf(allocationExpression("int32_t",
                Integer.toString(array.dimensions().get(0)))));
        emitMultiArrayChildren(output, ref(array.target()), array.leafType(), array.dimensions(), 1);
    }

    private void emitMultiArrayChildren(StringBuilder output, String parentHandle, ArrayElementType leafType,
                                        List<Integer> dimensions, int level) {
        if (level >= dimensions.size()) {
            return;
        }
        int count = dimensions.get(level - 1);
        boolean leaf = level == dimensions.size() - 1;
        for (int index = 0; index < count; index++) {
            String slot = "reinterpret_cast<int32_t*>(" + parentHandle + ")[" + index + "]";
            String elementCppType = leaf ? cppType(leafType) : "int32_t";
            output.append("  ").append(slot).append(" = ")
                    .append(handleOf(allocationExpression(elementCppType,
                            Integer.toString(dimensions.get(level)))))
                    .append(";\n");
            if (!leaf) {
                emitMultiArrayChildren(output, slot, leafType, dimensions, level + 1);
            }
        }
    }

    private String allocationExpression(String cppType, String count) {
        return "reinterpret_cast<" + cppType + "*>(juno_alloc(sizeof(" + cppType + ") * (" + count
                + "), alignof(" + cppType + ")))";
    }

    private String localRef(int local, JunoType type, boolean typedLocals) {
        if (!typedLocals) {
            return "locals[" + local + "]";
        }
        String member = switch (type) {
            case INT32 -> "i32";
            case INT64 -> "i64";
            case FLOAT32 -> "f32";
            case FLOAT64 -> "f64";
        };
        return "locals[" + local + "]." + member;
    }

    private String floatLiteral(float value) {
        if (Float.isNaN(value)) {
            return "NAN";
        }
        if (value == Float.POSITIVE_INFINITY) {
            return "INFINITY";
        }
        if (value == Float.NEGATIVE_INFINITY) {
            return "-INFINITY";
        }
        return Float.toHexString(value) + "f";
    }

    private String doubleLiteral(double value) {
        if (Double.isNaN(value)) {
            return "NAN";
        }
        if (value == Double.POSITIVE_INFINITY) {
            return "INFINITY";
        }
        if (value == Double.NEGATIVE_INFINITY) {
            return "-INFINITY";
        }
        return Double.toHexString(value);
    }

    private String floatBinaryExpression(FloatBinaryOp operation, Value left, Value right) {
        if (operation == FloatBinaryOp.REMAINDER) {
            return "fmodf(" + ref(left) + ", " + ref(right) + ")";
        }
        String operator = switch (operation) {
            case ADD -> "+";
            case SUBTRACT -> "-";
            case MULTIPLY -> "*";
            case DIVIDE -> "/";
            case REMAINDER -> throw new IllegalStateException("handled above");
        };
        return ref(left) + " " + operator + " " + ref(right);
    }

    private String doubleBinaryExpression(FloatBinaryOp operation, Value left, Value right) {
        if (operation == FloatBinaryOp.REMAINDER) {
            return "fmod(" + ref(left) + ", " + ref(right) + ")";
        }
        String operator = switch (operation) {
            case ADD -> "+";
            case SUBTRACT -> "-";
            case MULTIPLY -> "*";
            case DIVIDE -> "/";
            case REMAINDER -> throw new IllegalStateException("handled above");
        };
        return ref(left) + " " + operator + " " + ref(right);
    }

    /** Reconstructs a signed 64-bit value from its two 32-bit halves (see {@link IrInstruction.LongConst}). */
    private String combineLong(Value low, Value high) {
        return "static_cast<int64_t>((static_cast<uint64_t>(static_cast<uint32_t>(" + ref(high) + ")) << 32) | "
                + "static_cast<uint64_t>(static_cast<uint32_t>(" + ref(low) + ")))";
    }

    private String splitLow(String int64Expression) {
        return "static_cast<int32_t>(static_cast<uint32_t>(static_cast<uint64_t>(" + int64Expression + ")))";
    }

    private String splitHigh(String int64Expression) {
        return "static_cast<int32_t>(static_cast<uint32_t>(static_cast<uint64_t>(" + int64Expression + ") >> 32))";
    }

    private void emitTerminator(StringBuilder output, int blockStart, IrTerminator terminator,
                                IrInstruction.Compare foldedCompare, Optional<ArrayElementType> returnArrayType) {
        switch (terminator) {
            case IrTerminator.Jump jump -> {
                emitRuntimePollForBackedge(output, blockStart, List.of(jump.target()));
                output.append("  goto juno_pc_").append(jump.target()).append(";\n");
            }
            case IrTerminator.Branch branch -> {
                emitRuntimePollForBackedge(output, blockStart,
                        List.of(branch.trueTarget(), branch.falseTarget()));
                String condition = foldedCompare != null
                        ? ref(foldedCompare.left()) + " " + operatorFor(foldedCompare.condition()) + " " + ref(foldedCompare.right())
                        : ref(branch.condition()) + " != 0";
                output.append("  if (").append(condition).append(") goto juno_pc_").append(branch.trueTarget()).append(";\n")
                        .append("  goto juno_pc_").append(branch.falseTarget()).append(";\n");
            }
            case IrTerminator.Return returned -> {
                if (returned.value().isEmpty()) {
                    output.append("  return;\n");
                } else if (returnArrayType.isPresent()) {
                    output.append("  return reinterpret_cast<").append(cppType(returnArrayType.get())).append("*>(")
                            .append(ref(returned.value().get())).append(");\n");
                } else {
                    output.append("  return ").append(ref(returned.value().get())).append(";\n");
                }
            }
            case IrTerminator.Switch switched -> {
                List<Integer> targets = new ArrayList<>(switched.targets());
                targets.add(switched.defaultTarget());
                emitRuntimePollForBackedge(output, blockStart, targets);
                output.append("  switch (").append(ref(switched.selector())).append(") {\n");
                for (int index = 0; index < switched.keys().size(); index++) {
                    output.append("    case ").append(switched.keys().get(index)).append(": goto juno_pc_")
                            .append(switched.targets().get(index)).append(";\n");
                }
                output.append("    default: goto juno_pc_").append(switched.defaultTarget()).append(";\n")
                        .append("  }\n");
            }
        }
    }

    /**
     * Emits a {@code yield()} call before any terminator that closes a loop (a jump/branch/switch target at or
     * before the current block's start). Arduino's {@code delay()} already polls the runtime via its own
     * internal {@code yield()} calls, but a tight loop with no {@code delay()} — or one that never touches
     * {@code Serial} at all — would otherwise starve UNO R4's USB servicing (see the generated {@code yield()}
     * in {@link #runtimeHelpers()}) until the loop happens to exit.
     */
    private void emitRuntimePollForBackedge(StringBuilder output, int blockStart, List<Integer> targets) {
        if (targets.stream().anyMatch(target -> target <= blockStart)) {
            output.append("  yield();\n");
        }
    }

    private void emitUserCall(StringBuilder output, IrInstruction.Call call) {
        Descriptor calleeDescriptor = Descriptor.parse(call.method().descriptor());
        List<String> parameterTypes = calleeDescriptor.parameters();
        Optional<ArrayElementType> returnArrayType = arrayElementTypeOf(calleeDescriptor.returnType());
        output.append("  ");
        if (call.target().isPresent()) {
            output.append(ref(call.target().get())).append(" = ");
        }
        if (returnArrayType.isPresent()) {
            output.append(handleOf(callExpression(call, parameterTypes)));
        } else {
            output.append(callExpression(call, parameterTypes));
        }
        output.append(";\n");
    }

    private String callExpression(IrInstruction.Call call, List<String> parameterTypes) {
        StringBuilder expression = new StringBuilder(CppNames.method(call.method())).append('(');
        List<Value> arguments = call.arguments();
        boolean instanceCall = arguments.size() == parameterTypes.size() + 1;
        for (int index = 0; index < arguments.size(); index++) {
            if (index > 0) {
                expression.append(", ");
            }
            if (instanceCall && index == 0) {
                expression.append(ref(arguments.get(index)));
                continue;
            }
            String parameterType = parameterTypes.get(index - (instanceCall ? 1 : 0));
            if (Descriptor.isArrayType(parameterType)) {
                expression.append("reinterpret_cast<").append(cppType(arrayElementTypeOf(parameterType).orElseThrow()))
                        .append("*>(").append(ref(arguments.get(index))).append(')');
            } else {
                expression.append(ref(arguments.get(index)));
            }
        }
        return expression.append(')').toString();
    }

    private void emitIntrinsicCall(StringBuilder output, IrInstruction.IntrinsicCall call) {
        output.append("  {\n");
        List<Value> arguments = call.arguments();
        for (int index = 0; index < arguments.size(); index++) {
            output.append("    int32_t call_arg").append(index).append(" = ").append(ref(arguments.get(index))).append(";\n");
        }
        if (call.receiver().isPresent()) {
            output.append("    int32_t call_receiver = ").append(ref(call.receiver().get())).append(";\n");
        }
        output.append("    ");
        if (call.target().isPresent()) {
            output.append(ref(call.target().get())).append(" = ");
        }
        output.append(intrinsicExpression(call.intrinsic())).append(";\n  }\n");
    }

    private String intrinsicExpression(Intrinsic intrinsic) {
        return switch (intrinsic) {
            case GPIO_PIN_MODE -> "pinMode(call_arg0, call_arg1)";
            case GPIO_DIGITAL_WRITE -> "digitalWrite(call_arg0, call_arg1 ? HIGH : LOW)";
            case GPIO_DIGITAL_READ -> "static_cast<int32_t>(digitalRead(call_arg0) == HIGH)";
            case GPIO_ANALOG_READ -> "static_cast<int32_t>(analogRead(call_arg0))";
            case GPIO_ANALOG_WRITE -> "analogWrite(call_arg0, call_arg1)";
            case GPIO_TOGGLE -> "digitalWrite(call_arg0, digitalRead(call_arg0) == HIGH ? LOW : HIGH)";
            case DELAY_MILLIS -> "delay(static_cast<unsigned long>(call_arg0))";
            case DELAY_MICROS -> "delayMicroseconds(static_cast<unsigned int>(call_arg0))";
            case CLOCK_MILLIS -> "static_cast<int32_t>(millis())";
            case CLOCK_MICROS -> "static_cast<int32_t>(micros())";
            case DIGITAL_OUTPUT_OF -> "juno_digital_output_of(call_arg0)";
            case DIGITAL_OUTPUT_HIGH -> "digitalWrite(call_receiver, HIGH)";
            case DIGITAL_OUTPUT_LOW -> "digitalWrite(call_receiver, LOW)";
            case DIGITAL_OUTPUT_TOGGLE -> "digitalWrite(call_receiver, digitalRead(call_receiver) == HIGH ? LOW : HIGH)";
            case DIGITAL_OUTPUT_IS_HIGH -> "static_cast<int32_t>(digitalRead(call_receiver) == HIGH)";
            case LED_MATRIX_BEGIN -> "juno_led_matrix_begin()";
            case LED_MATRIX_LOAD_FRAME -> "juno_led_matrix_load_frame(call_arg0, call_arg1, call_arg2)";
            case LED_MATRIX_CLEAR -> "juno_led_matrix_clear()";
            case SERIAL_BEGIN -> "Serial.begin(static_cast<unsigned long>(call_arg0))";
            case SERIAL_PRINT -> "Serial.print(call_arg0)";
            case SERIAL_PRINTLN -> "Serial.println(call_arg0)";
            case MOUSE_BEGIN -> "Mouse.begin()";
            case MOUSE_MOVE -> "Mouse.move(static_cast<signed char>(call_arg0), static_cast<signed char>(call_arg1))";
        };
    }

    private String unaryExpression(IrInstruction.Unary unary) {
        String operand = ref(unary.value());
        return switch (unary.operation()) {
            case NEGATE -> "juno_ineg(" + operand + ")";
            case TO_BYTE -> "juno_i2b(" + operand + ")";
            case TO_CHAR -> "static_cast<uint16_t>(" + operand + ")";
            case TO_SHORT -> "juno_i2s(" + operand + ")";
        };
    }

    private String helperFor(BinaryOp operation) {
        return switch (operation) {
            case ADD -> "juno_iadd";
            case SUBTRACT -> "juno_isub";
            case MULTIPLY -> "juno_imul";
            case DIVIDE -> "juno_idiv";
            case REMAINDER -> "juno_irem";
            case SHIFT_LEFT -> "juno_ishl";
            case SHIFT_RIGHT -> "juno_ishr";
            case UNSIGNED_SHIFT_RIGHT -> "juno_iushr";
            case AND -> "juno_iand";
            case OR -> "juno_ior";
            case XOR -> "juno_ixor";
        };
    }

    private String longHelperFor(BinaryOp operation) {
        return switch (operation) {
            case ADD -> "juno_ladd";
            case SUBTRACT -> "juno_lsub";
            case MULTIPLY -> "juno_lmul";
            case DIVIDE -> "juno_ldiv";
            case REMAINDER -> "juno_lrem";
            case AND -> "juno_land";
            case OR -> "juno_lor";
            case XOR -> "juno_lxor";
            case SHIFT_LEFT, SHIFT_RIGHT, UNSIGNED_SHIFT_RIGHT ->
                    throw new IllegalStateException("Long shifts use longShiftHelperFor, not longHelperFor: " + operation);
        };
    }

    private String longShiftHelperFor(BinaryOp operation) {
        return switch (operation) {
            case SHIFT_LEFT -> "juno_lshl";
            case SHIFT_RIGHT -> "juno_lshr";
            case UNSIGNED_SHIFT_RIGHT -> "juno_lushr";
            default -> throw new IllegalStateException("Not a long shift operation: " + operation);
        };
    }

    private String operatorFor(Condition condition) {
        return switch (condition) {
            case EQUAL -> "==";
            case NOT_EQUAL -> "!=";
            case LESS_THAN -> "<";
            case GREATER_EQUAL -> ">=";
            case GREATER_THAN -> ">";
            case LESS_EQUAL -> "<=";
        };
    }

    private void assign(StringBuilder output, Value target, String expression) {
        output.append("  ").append(ref(target)).append(" = ").append(expression).append(";\n");
    }

    private String ref(Value value) {
        return "v" + value.id();
    }

    /**
     * Converts a pointer expression to the {@code int32_t} handle representation every array reference is
     * stored as. {@code reinterpret_cast<int32_t>(pointer)} is only valid when a pointer fits in 32 bits —
     * true on the actual Cortex-M4 target, but not on a 64-bit host, where syntax checks (and any other
     * non-target compilation) would reject it. Going through {@code intptr_t} first is valid on both: exact
     * on the 32-bit target, and merely truncating (never executed there) on a 64-bit host.
     */
    private String handleOf(String pointerExpression) {
        return "static_cast<int32_t>(reinterpret_cast<intptr_t>(" + pointerExpression + "))";
    }

    private String prototype(IrMethod method) {
        Descriptor descriptor = Descriptor.parse(method.reference().descriptor());
        String returnType;
        if (descriptor.returnsVoid()) {
            returnType = "void";
        } else if (Descriptor.isLong(descriptor.returnType())) {
            returnType = "int64_t";
        } else if (Descriptor.isFloat(descriptor.returnType())) {
            returnType = "float";
        } else if (Descriptor.isDouble(descriptor.returnType())) {
            returnType = "double";
        } else {
            Optional<ArrayElementType> arrayReturn = arrayElementTypeOf(descriptor.returnType());
            returnType = arrayReturn.map(type -> cppType(type) + "*").orElse("int32_t");
        }
        StringBuilder result = new StringBuilder("static ").append(returnType).append(' ')
                .append(CppNames.method(method.reference())).append('(');
        boolean hasParameter = false;
        if (!method.isStatic()) {
            result.append("int32_t arg_receiver");
            hasParameter = true;
        }
        List<String> parameterTypes = descriptor.parameters();
        for (int i = 0; i < parameterTypes.size(); i++) {
            if (hasParameter) {
                result.append(", ");
            }
            String parameterType = parameterTypes.get(i);
            Optional<ArrayElementType> arrayParam = arrayElementTypeOf(parameterType);
            String cppParameter = Descriptor.isLong(parameterType)
                    ? "int64_t arg"
                    : Descriptor.isDouble(parameterType)
                    ? "double arg"
                    : Descriptor.isFloat(parameterType)
                            ? "float arg"
                            : arrayParam.map(type -> cppType(type) + "* arg").orElse("int32_t arg");
            result.append(cppParameter).append(i);
            hasParameter = true;
        }
        return result.append(')').toString();
    }

    private Optional<ArrayElementType> arrayElementTypeOf(String type) {
        if (!Descriptor.isArrayType(type)) {
            return Optional.empty();
        }
        return ArrayElementType.fromArrayDescriptor(type);
    }

    private String cppType(ArrayElementType elementType) {
        return switch (elementType) {
            case BYTE -> "int8_t";
            case CHAR -> "uint16_t";
            case SHORT -> "int16_t";
            case INT -> "int32_t";
            case REFERENCE -> "int32_t";
            case LONG -> "int64_t";
            case FLOAT -> "float";
            case DOUBLE -> "double";
        };
    }

    private String floatingPointHelpers() {
        return """
                static int32_t juno_f2i(float value) {
                  if (isnan(value)) return 0;
                  if (value >= 0x1.0p31f) return INT32_MAX;
                  if (value <= -0x1.0p31f) return INT32_MIN;
                  return static_cast<int32_t>(value);
                }

                static int32_t juno_d2i(double value) {
                  if (isnan(value)) return 0;
                  if (value >= 0x1.0p31) return INT32_MAX;
                  if (value <= -0x1.0p31) return INT32_MIN;
                  return static_cast<int32_t>(value);
                }
                static int64_t juno_f2l(float value) {
                  if (isnan(value)) return 0;
                  if (value >= 0x1.0p63f) return INT64_MAX;
                  if (value <= -0x1.0p63f) return INT64_MIN;
                  return static_cast<int64_t>(value);
                }
                static int64_t juno_d2l(double value) {
                  if (isnan(value)) return 0;
                  if (value >= 0x1.0p63) return INT64_MAX;
                  if (value <= -0x1.0p63) return INT64_MIN;
                  return static_cast<int64_t>(value);
                }

                """;
    }

    private String runtimeHelpers() {
        return """
                // Overrides the core's weak yield(): Serial's bool conversion is UNO R4's supported hook into
                // TinyUSB's tud_task(), so this keeps USB serviced from every yield() call site (delay() and
                // loop backedges), not just programs that call Serial directly.
                void yield() {
                #ifndef NO_USB
                  static_cast<void>(static_cast<bool>(Serial));
                #endif
                }

                [[noreturn]] static void juno_panic() {
                  noInterrupts();
                  for (;;) {}
                }

                static uint8_t juno_arena[${JUNO_ARENA_CAPACITY}] __attribute__((aligned(8)));
                static uint32_t juno_arena_used = 0;

                static void* juno_alloc(uint32_t size, uint32_t alignment) {
                  uint32_t aligned = (juno_arena_used + alignment - 1u) & ~(alignment - 1u);
                  if (aligned > sizeof(juno_arena) || size > sizeof(juno_arena) - aligned) juno_panic();
                  uint8_t* memory = &juno_arena[aligned];
                  for (uint32_t index = 0; index < size; index++) memory[index] = 0;
                  juno_arena_used = aligned + size;
                  return memory;
                }

                static int32_t juno_iadd(int32_t a, int32_t b) {
                  return static_cast<int32_t>(static_cast<uint32_t>(a) + static_cast<uint32_t>(b));
                }
                static int32_t juno_isub(int32_t a, int32_t b) {
                  return static_cast<int32_t>(static_cast<uint32_t>(a) - static_cast<uint32_t>(b));
                }
                static int32_t juno_imul(int32_t a, int32_t b) {
                  return static_cast<int32_t>(static_cast<uint32_t>(a) * static_cast<uint32_t>(b));
                }
                static int32_t juno_idiv(int32_t a, int32_t b) {
                  if (b == 0) juno_panic();
                  if (a == INT32_MIN && b == -1) return INT32_MIN;
                  return a / b;
                }
                static int32_t juno_irem(int32_t a, int32_t b) {
                  if (b == 0) juno_panic();
                  if (a == INT32_MIN && b == -1) return 0;
                  return a % b;
                }
                static int32_t juno_ineg(int32_t value) {
                  return static_cast<int32_t>(0u - static_cast<uint32_t>(value));
                }
                static int32_t juno_ishl(int32_t a, int32_t b) {
                  return static_cast<int32_t>(static_cast<uint32_t>(a) << (b & 31));
                }
                static int32_t juno_ishr(int32_t a, int32_t b) {
                  uint32_t shift = static_cast<uint32_t>(b) & 31u;
                  uint32_t value = static_cast<uint32_t>(a);
                  if (shift == 0 || a >= 0) return static_cast<int32_t>(value >> shift);
                  return static_cast<int32_t>((value >> shift) | (~0u << (32u - shift)));
                }
                static int32_t juno_iushr(int32_t a, int32_t b) {
                  return static_cast<int32_t>(static_cast<uint32_t>(a) >> (b & 31));
                }
                static int32_t juno_iand(int32_t a, int32_t b) { return a & b; }
                static int32_t juno_ior(int32_t a, int32_t b) { return a | b; }
                static int32_t juno_ixor(int32_t a, int32_t b) { return a ^ b; }
                static int32_t juno_i2b(int32_t value) {
                  uint32_t narrowed = static_cast<uint32_t>(value) & 0xffu;
                  return static_cast<int32_t>(narrowed >= 0x80u ? narrowed | 0xffffff00u : narrowed);
                }
                static int32_t juno_i2s(int32_t value) {
                  uint32_t narrowed = static_cast<uint32_t>(value) & 0xffffu;
                  return static_cast<int32_t>(narrowed >= 0x8000u ? narrowed | 0xffff0000u : narrowed);
                }
                static int32_t juno_digital_output_of(int32_t pin) {
                  pinMode(pin, OUTPUT);
                  return pin;
                }

                static int64_t juno_ladd(int64_t a, int64_t b) {
                  return static_cast<int64_t>(static_cast<uint64_t>(a) + static_cast<uint64_t>(b));
                }
                static int64_t juno_lsub(int64_t a, int64_t b) {
                  return static_cast<int64_t>(static_cast<uint64_t>(a) - static_cast<uint64_t>(b));
                }
                static int64_t juno_lmul(int64_t a, int64_t b) {
                  return static_cast<int64_t>(static_cast<uint64_t>(a) * static_cast<uint64_t>(b));
                }
                static int64_t juno_ldiv(int64_t a, int64_t b) {
                  if (b == 0) juno_panic();
                  if (a == INT64_MIN && b == -1) return INT64_MIN;
                  return a / b;
                }
                static int64_t juno_lrem(int64_t a, int64_t b) {
                  if (b == 0) juno_panic();
                  if (a == INT64_MIN && b == -1) return 0;
                  return a % b;
                }
                static int64_t juno_lneg(int64_t value) {
                  return static_cast<int64_t>(0ull - static_cast<uint64_t>(value));
                }
                static int64_t juno_lshl(int64_t a, int32_t b) {
                  return static_cast<int64_t>(static_cast<uint64_t>(a) << (b & 63));
                }
                static int64_t juno_lshr(int64_t a, int32_t b) {
                  uint32_t shift = static_cast<uint32_t>(b) & 63u;
                  uint64_t value = static_cast<uint64_t>(a);
                  if (shift == 0 || a >= 0) return static_cast<int64_t>(value >> shift);
                  return static_cast<int64_t>((value >> shift) | (~0ull << (64u - shift)));
                }
                static int64_t juno_lushr(int64_t a, int32_t b) {
                  return static_cast<int64_t>(static_cast<uint64_t>(a) >> (b & 63));
                }
                static int64_t juno_land(int64_t a, int64_t b) { return a & b; }
                static int64_t juno_lor(int64_t a, int64_t b) { return a | b; }
                static int64_t juno_lxor(int64_t a, int64_t b) { return a ^ b; }

                """.replace("${JUNO_ARENA_CAPACITY}", Integer.toString(RuntimeLimits.ARENA_CAPACITY_BYTES));
    }

    private String ledMatrixHelpers() {
        return """
                ArduinoLEDMatrix juno_led_matrix;
                static void juno_led_matrix_begin() {
                  juno_led_matrix.begin();
                }
                static void juno_led_matrix_load_frame(int32_t word0, int32_t word1, int32_t word2) {
                  const uint32_t frame[3] = {
                    static_cast<uint32_t>(word0),
                    static_cast<uint32_t>(word1),
                    static_cast<uint32_t>(word2)
                  };
                  juno_led_matrix.loadFrame(frame);
                }
                static void juno_led_matrix_clear() {
                  const uint32_t frame[3] = {0, 0, 0};
                  juno_led_matrix.loadFrame(frame);
                }

                """;
    }
}
