package io.github.jabrena.juno.backend;

import io.github.jabrena.juno.RuntimeLimits;
import io.github.jabrena.juno.board.Board;
import io.github.jabrena.juno.board.Capability;
import io.github.jabrena.juno.intrinsic.Intrinsic;

import java.util.List;
import java.util.Optional;
import java.util.Set;

/**
 * Generates the {@code extern "C"} C++ runtime shim compiled alongside the generated assembly:
 * wrappers around things the assembly can't call directly — the arena allocator/panic handler and
 * {@code ArduinoLEDMatrix} (a C++-only object with inline-only methods and private timer/frame
 * state — no stable symbol to call without knowing its private layout) — plus every optional
 * helper block ({@link ShimLibraries}, {@link NetworkShimLibraries}) and library include the
 * lowered program's {@link ShimFeature}s call for. Optional parts are decided here, at
 * Java-string-generation time, so an unused feature costs no flash, RAM or build dependency.
 */
final class RuntimeShim {
    private final Board board;
    private final CoreRuntime core;
    private final boolean gcLoggingEnabled;
    private final Set<ShimFeature> features;
    private final Set<Intrinsic> usedMath;
    private final List<String> throwableClasses;
    private final boolean usesWatchdog;
    private final int watchdogTimeoutMillis;

    /**
     * @param core {@code board}'s per-core runtime glue (see {@link CoreRuntime#of})
     * @param features every optional shim feature the lowered program uses
     * @param usedMath every {@code java.lang.Math} intrinsic the lowered program calls
     * @param watchdogTimeoutMillis the entry point's {@code @Watchdog} timeout, if it has one
     */
    RuntimeShim(Board board, CoreRuntime core, boolean gcLoggingEnabled, Set<ShimFeature> features,
                Set<Intrinsic> usedMath, List<String> throwableClasses, Optional<Integer> watchdogTimeoutMillis) {
        this.board = board;
        this.core = core;
        this.gcLoggingEnabled = gcLoggingEnabled;
        this.features = features;
        this.usedMath = usedMath;
        this.throwableClasses = throwableClasses;
        this.usesWatchdog = watchdogTimeoutMillis.isPresent();
        this.watchdogTimeoutMillis = watchdogTimeoutMillis.orElse(0);
    }

    String generate() {
        StringBuilder shim = new StringBuilder();
        shim.append("""
                // Generated by Juno's Thumb-2 assembly backend. Do not edit.
                // Author: Juan Antonio Brena Moral
                #include <Arduino.h>
                #include <stdint.h>
                ${JUNO_LED_MATRIX_INCLUDE}// The UNO R4 core compiles this shim with -mfloat-abi=hard, but Juno's generated assembly
                // passes float/double values in core registers; every shim function taking or returning one
                // opts back into the base procedure-call standard so both sides agree.
                #if defined(__arm__)
                #define JUNO_ASM_ABI __attribute__((pcs("aapcs")))
                #else
                #define JUNO_ASM_ABI
                #endif
                """.replace("${JUNO_LED_MATRIX_INCLUDE}",
                board.supports(Capability.LED_MATRIX) ? "#include \"Arduino_LED_Matrix.h\"\n" : ""));
        appendIncludes(shim);
        shim.append(coreRuntime());
        appendHelpers(shim);
        return shim.toString();
    }

    private boolean uses(ShimFeature feature) {
        return features.contains(feature);
    }

    private boolean usesAny(ShimFeature... candidates) {
        for (ShimFeature candidate : candidates) {
            if (features.contains(candidate)) {
                return true;
            }
        }
        return false;
    }

    private void appendIncludes(StringBuilder shim) {
        // Mouse is an optional library (arduino-cli lib install Mouse), unlike the core-bundled
        // LED matrix/Serial above — only pull it in when the program actually uses it, so every
        // other generated sketch keeps compiling without that library installed.
        if (uses(ShimFeature.MOUSE)) {
            shim.append("#include <Mouse.h>\n");
        }
        if (uses(ShimFeature.SERVO)) {
            shim.append("#include <Servo.h>\n");
        }
        // ArduinoBLE is another optional library (arduino-cli lib install ArduinoBLE), like Mouse above.
        if (uses(ShimFeature.LEGO_POWERED_UP)) {
            shim.append("#include <ArduinoBLE.h>\n");
        }
        if (usesAny(ShimFeature.WIFI, ShimFeature.UDP, ShimFeature.HTTP, ShimFeature.HTTPS, ShimFeature.HTTP_SERVER,
                ShimFeature.SMTP, ShimFeature.SMTP_TLS, ShimFeature.POP3)) {
            shim.append(core.wifiIncludes(uses(ShimFeature.UDP)));
        }
        if (uses(ShimFeature.SD)) {
            shim.append("#include <SPI.h>\n#include <SdFat.h>\n");
        }
        if (uses(ShimFeature.THREADS)) {
            shim.append(core.threadIncludes());
        }
        if (usesAny(ShimFeature.HTTPS, ShimFeature.SMTP_TLS, ShimFeature.POP3)) {
            shim.append(core.httpsInclude());
        }
        // ESP_SSLClient is a third-party library (arduino-cli lib install ESP_SSLClient), the same
        // manual-install pattern as Mouse above: the UNO R4 WiFi's native WiFiSSLClient can only
        // negotiate TLS from the first byte, so Smtp's STARTTLS upgrade (mail submission on port
        // 587) needs this wrapper around a plain WiFiClient instead.
        if (uses(ShimFeature.SMTP)) {
            shim.append("#include <ESP_SSLClient.h>\n");
        }
        if (uses(ShimFeature.HTTP_SERVER)) {
            shim.append("#include <new>\n");
        }
        if (usesAny(ShimFeature.HTTP, ShimFeature.HTTPS, ShimFeature.HTTP_SERVER, ShimFeature.JSON,
                ShimFeature.RUNTIME_STRINGS, ShimFeature.SMTP, ShimFeature.SMTP_TLS, ShimFeature.POP3,
                ShimFeature.SD)) {
            shim.append("#include <string.h>\n");
        }
        if (usesAny(ShimFeature.FLOAT, ShimFeature.DOUBLE, ShimFeature.JSON, ShimFeature.RUNTIME_STRINGS,
                ShimFeature.STRING_BUILDER) || !usedMath.isEmpty()) {
            shim.append("#include <math.h>\n");
        }
        // WDT (like Arduino_LED_Matrix above) is bundled with the renesas_uno core, not a separate
        // library install — only pulled in for programs whose entry-point class carries @Watchdog.
        if (usesWatchdog) {
            shim.append("#include <WDT.h>\n");
        }
    }

    /** Panic handler, yield hook, watchdog, arena allocator and collector, LED matrix and Serial. */
    private String coreRuntime() {
        // Emitted (or not) once here, at Java-string-generation time — like every other optional
        // shim feature (ShimFeature.MOUSE, ShimFeature.WIFI, ...) — rather than a C++-level runtime branch, so a
        // program compiled without --gc-log/juno.gcLog pays zero extra flash/RAM/Serial time for it.
        String gcLogBefore = gcLoggingEnabled ? "uint32_t junoGcLogUsedBefore = juno_arena_used;" : "";
        String gcLogAfter = gcLoggingEnabled
                ? "Serial.print(\"[juno-gc] collect: used \"); Serial.print(junoGcLogUsedBefore); "
                        + "Serial.print(\" -> \"); Serial.println(juno_arena_used);"
                : "";
        String watchdogRefresh = usesWatchdog ? "WDT.refresh();" : "";
        String watchdogPanicMessage = usesWatchdog
                ? "Serial.println(\"[juno-watchdog] panic: board will reset via watchdog in "
                        + watchdogTimeoutMillis + "ms\");"
                : "";
        String watchdogBeginFunction = usesWatchdog
                ? "\nextern \"C\" void juno_watchdog_begin() {\n  WDT.begin(" + watchdogTimeoutMillis + "u);\n}\n"
                : "";
        // With threads every live thread's stack is a root, not just the one running (see ThreadRuntime).
        String gcStackScan = uses(ShimFeature.THREADS)
                ? "juno_thread_gc_scan(&stackMarker);"
                : "juno_gc_scan_range(&stackMarker, reinterpret_cast<const uint8_t*>(juno_gc_stack_top));";
        String gcThreadDeclaration = uses(ShimFeature.THREADS)
                ? "static void juno_thread_gc_scan(const uint8_t* marker);\n"
                : "";
        String ledMatrixFunctions = ledMatrixFunctions();
        String yieldFunction = core.yieldFunction();
        return """

                ${JUNO_YIELD_FUNCTION}extern "C" [[noreturn]] void juno_panic() {
                  // The watchdog diagnostic (if any) must print before noInterrupts(): USB CDC
                  // Serial relies on interrupts/yield() to actually flush bytes out, so anything
                  // printed after would be silently lost, same as the arena/bounds/etc. panics that
                  // already print their own diagnostic before calling this function.
                  ${JUNO_WATCHDOG_PANIC_MESSAGE}
                  noInterrupts();
                  for (;;) {}
                }
                ${JUNO_WATCHDOG_BEGIN_FUNCTION}
                static uint8_t juno_arena[${JUNO_ARENA_CAPACITY}] __attribute__((aligned(8)));
                static uint32_t juno_arena_used = 0;

                // Conservative mark/sweep collector (Boehm-GC style: no type tags, no compaction —
                // a conservative collector can't safely move objects since it can't tell a real
                // pointer from an int that happens to match a heap address). Every arena block
                // (allocated or free) has a 4-byte header immediately before the payload pointer
                // callers see, so juno_alloc's return value never changes shape: bit 31 is the mark
                // bit, bit 30 marks a free block, and the low 30 bits hold the block's padded
                // payload size (always a multiple of 4, so every header stays 4-byte aligned and the
                // block chain can be walked linearly). juno_gc_stack_top is written once, by the
                // generated entry-point prologue, with the live sp at program start — see
                // Thumb2AsmBackend.emitMethod; it bounds every future conservative stack scan. The
                // generated static range is scanned too, so reference-valued static fields are roots.
                extern "C" uintptr_t juno_gc_stack_top;
                extern "C" uint8_t juno_gc_static_start;
                extern "C" uint8_t juno_gc_static_end;
                ${JUNO_GC_THREAD_DECLARATION}
                static constexpr uint32_t JUNO_GC_MARK_BIT = 0x80000000u;
                static constexpr uint32_t JUNO_GC_FREE_BIT = 0x40000000u;
                static constexpr uint32_t JUNO_GC_SIZE_MASK = 0x3FFFFFFFu;
                static constexpr uint32_t JUNO_GC_NO_NEXT = 0xFFFFFFFFu;
                static constexpr uint32_t JUNO_GC_MIN_PAYLOAD = 4u;
                static constexpr uint32_t JUNO_GC_QUEUE_CAPACITY = 64u;

                static uint32_t juno_gc_free_list_head = JUNO_GC_NO_NEXT;
                static uint32_t juno_gc_queue[JUNO_GC_QUEUE_CAPACITY];
                static uint32_t juno_gc_queue_count = 0;
                static bool juno_gc_queue_overflowed = false;

                static uint32_t juno_gc_round_up4(uint32_t value) {
                  return (value + 3u) & ~3u;
                }

                static uint32_t* juno_gc_header_at(uint32_t offset) {
                  return reinterpret_cast<uint32_t*>(&juno_arena[offset]);
                }

                static uint32_t juno_gc_block_size(uint32_t header) {
                  return header & JUNO_GC_SIZE_MASK;
                }

                // A free block stores its free-list "next" offset in its own payload's first 4
                // bytes — only possible when the payload is at least JUNO_GC_MIN_PAYLOAD bytes;
                // smaller freed slivers are accepted v1 fragmentation and never linked.
                static void juno_gc_push_free(uint32_t offset, uint32_t payload) {
                  *juno_gc_header_at(offset) = payload | JUNO_GC_FREE_BIT;
                  if (payload >= JUNO_GC_MIN_PAYLOAD) {
                    *reinterpret_cast<uint32_t*>(&juno_arena[offset + 4u]) = juno_gc_free_list_head;
                    juno_gc_free_list_head = offset;
                  }
                }

                // First-fit search: unlinks and returns the offset of a free block whose payload is
                // at least `padded` bytes, splitting off a remainder block when the leftover is worth
                // keeping, or JUNO_GC_NO_NEXT if nothing free fits.
                static uint32_t juno_gc_take_free(uint32_t padded) {
                  uint32_t previous = JUNO_GC_NO_NEXT;
                  uint32_t offset = juno_gc_free_list_head;
                  while (offset != JUNO_GC_NO_NEXT) {
                    uint32_t header = *juno_gc_header_at(offset);
                    uint32_t payload = juno_gc_block_size(header);
                    uint32_t next = *reinterpret_cast<uint32_t*>(&juno_arena[offset + 4u]);
                    if (payload >= padded) {
                      if (previous == JUNO_GC_NO_NEXT) {
                        juno_gc_free_list_head = next;
                      } else {
                        *reinterpret_cast<uint32_t*>(&juno_arena[previous + 4u]) = next;
                      }
                      uint32_t leftover = payload - padded;
                      if (leftover >= 4u + JUNO_GC_MIN_PAYLOAD) {
                        *juno_gc_header_at(offset) = padded;
                        juno_gc_push_free(offset + 4u + padded, leftover - 4u);
                      } else {
                        *juno_gc_header_at(offset) = payload;
                      }
                      return offset;
                    }
                    previous = offset;
                    offset = next;
                  }
                  return JUNO_GC_NO_NEXT;
                }

                // Is `offset` really the start of a block in [0, juno_arena_used)? An O(n) linear
                // chain walk rather than a precomputed bitmap: Juno's target programs (LED matrix
                // animations, sensor loops) have small live-object counts, so this keeps the
                // allocator simple — revisit only if real-hardware testing shows GC pauses are slow.
                static bool juno_gc_is_block_start(uint32_t offset) {
                  uint32_t cursor = 0;
                  while (cursor < juno_arena_used) {
                    if (cursor == offset) return true;
                    if (cursor > offset) return false;
                    cursor += 4u + juno_gc_block_size(*juno_gc_header_at(cursor));
                  }
                  return false;
                }

                static void juno_gc_enqueue(uint32_t offset) {
                  if (juno_gc_queue_count < JUNO_GC_QUEUE_CAPACITY) {
                    juno_gc_queue[juno_gc_queue_count++] = offset;
                  } else {
                    juno_gc_queue_overflowed = true;
                  }
                }

                // Every word on the live stack, and every word of every marked object's payload, is
                // a possible reference: with no type tags, the collector can't tell a real pointer
                // from an int that happens to match a heap address, so it treats anything that lines
                // up with a real, currently-allocated block's start as live.
                static void juno_gc_mark_candidate(uintptr_t word) {
                  uintptr_t base = reinterpret_cast<uintptr_t>(juno_arena);
                  if (word < base + 4u || word >= base + juno_arena_used) return;
                  uintptr_t relative = word - base;
                  if ((relative & 3u) != 0u) return;
                  uint32_t offset = static_cast<uint32_t>(relative) - 4u;
                  if (!juno_gc_is_block_start(offset)) return;
                  uint32_t header = *juno_gc_header_at(offset);
                  if ((header & JUNO_GC_FREE_BIT) != 0u || (header & JUNO_GC_MARK_BIT) != 0u) return;
                  *juno_gc_header_at(offset) = header | JUNO_GC_MARK_BIT;
                  juno_gc_enqueue(offset);
                }

                // Reads `sizeof(uintptr_t)`-wide, natively-aligned words so this same collector code
                // correctly recognizes real pointer values both on the 32-bit Cortex-M4 target and
                // when this shim is compiled and executed natively (e.g. by host-side tests) on a
                // 64-bit machine.
                static void juno_gc_scan_range(const uint8_t* from, const uint8_t* to) {
                  uintptr_t start = (reinterpret_cast<uintptr_t>(from) + sizeof(uintptr_t) - 1u)
                      & ~(sizeof(uintptr_t) - 1u);
                  uintptr_t end = reinterpret_cast<uintptr_t>(to);
                  for (uintptr_t cursor = start; cursor + sizeof(uintptr_t) <= end;
                       cursor += sizeof(uintptr_t)) {
                    juno_gc_mark_candidate(*reinterpret_cast<const uintptr_t*>(cursor));
                  }
                }

                static void juno_gc_scan_block_payload(uint32_t offset) {
                  uint32_t payload = juno_gc_block_size(*juno_gc_header_at(offset));
                  juno_gc_scan_range(&juno_arena[offset + 4u], &juno_arena[offset + 4u + payload]);
                }

                static void juno_gc_mark() {
                  juno_gc_queue_count = 0;
                  juno_gc_queue_overflowed = false;
                  // The address of a local variable is a portable, widely-used stand-in for "the
                  // current stack pointer" (the same technique Boehm-GC itself uses): it sits inside
                  // this function's own frame, deeper than every live Java frame, so scanning from
                  // here up to juno_gc_stack_top is always a safe superset of the true live stack.
                  uint8_t stackMarker;
                  juno_gc_scan_range(&juno_gc_static_start, &juno_gc_static_end);
                  ${JUNO_GC_STACK_SCAN}
                  uint32_t index = 0;
                  while (index < juno_gc_queue_count) {
                    juno_gc_scan_block_payload(juno_gc_queue[index]);
                    index++;
                  }
                  // Bounded work-queue overflow is a safety net, not the common case: fall back to a
                  // fixed-point rescan of the whole chain until a full pass finds nothing new.
                  bool rescanning = juno_gc_queue_overflowed;
                  while (rescanning) {
                    juno_gc_queue_overflowed = false;
                    bool changed = false;
                    uint32_t cursor = 0;
                    while (cursor < juno_arena_used) {
                      uint32_t header = *juno_gc_header_at(cursor);
                      uint32_t size = juno_gc_block_size(header);
                      if ((header & JUNO_GC_FREE_BIT) == 0u && (header & JUNO_GC_MARK_BIT) != 0u) {
                        uint32_t before = juno_gc_queue_count;
                        juno_gc_scan_block_payload(cursor);
                        while (before < juno_gc_queue_count) {
                          juno_gc_scan_block_payload(juno_gc_queue[before]);
                          before++;
                        }
                        if (juno_gc_queue_count > 0) changed = true;
                        juno_gc_queue_count = 0;
                      }
                      cursor += 4u + size;
                    }
                    rescanning = juno_gc_queue_overflowed && changed;
                  }
                }

                // Rebuilds the free list from scratch: walks the block chain in ascending address
                // order, coalescing each run of free-or-unmarked blocks into one free-list node
                // (adjacent dead blocks merge for free, since sweep already visits them in order),
                // clearing mark bits on survivors, and handing a trailing dead run straight back to
                // the bump allocator instead of free-listing it.
                static void juno_gc_sweep() {
                  juno_gc_free_list_head = JUNO_GC_NO_NEXT;
                  uint32_t cursor = 0;
                  uint32_t runStart = JUNO_GC_NO_NEXT;
                  while (cursor < juno_arena_used) {
                    uint32_t header = *juno_gc_header_at(cursor);
                    uint32_t size = juno_gc_block_size(header);
                    bool dead = (header & JUNO_GC_FREE_BIT) != 0u || (header & JUNO_GC_MARK_BIT) == 0u;
                    if (dead) {
                      if (runStart == JUNO_GC_NO_NEXT) runStart = cursor;
                    } else {
                      *juno_gc_header_at(cursor) = size;
                      if (runStart != JUNO_GC_NO_NEXT) {
                        juno_gc_push_free(runStart, cursor - runStart - 4u);
                        runStart = JUNO_GC_NO_NEXT;
                      }
                    }
                    cursor += 4u + size;
                  }
                  if (runStart != JUNO_GC_NO_NEXT) {
                    juno_arena_used = runStart;
                  }
                }

                static void juno_gc_collect() {
                  ${JUNO_GC_LOG_BEFORE}
                  juno_gc_mark();
                  juno_gc_sweep();
                  ${JUNO_GC_LOG_AFTER}
                }

                static void* juno_gc_try_allocate(uint32_t padded) {
                  uint32_t offset = juno_gc_take_free(padded);
                  if (offset == JUNO_GC_NO_NEXT) {
                    if (juno_arena_used + 4u + padded > sizeof(juno_arena)) return nullptr;
                    offset = juno_arena_used;
                    *juno_gc_header_at(offset) = padded;
                    juno_arena_used += 4u + padded;
                  }
                  return &juno_arena[offset + 4u];
                }

                extern "C" void* juno_alloc(uint32_t size, uint32_t alignment) {
                  if (alignment > 4u) juno_panic();
                  uint32_t padded = juno_gc_round_up4(size);
                  void* memory = juno_gc_try_allocate(padded);
                  if (memory == nullptr) {
                    juno_gc_collect();
                    memory = juno_gc_try_allocate(padded);
                  }
                  if (memory == nullptr) {
                    // Unconditional (unlike --gc-log's per-collection lines): a panic is rare and
                    // catastrophic, so the diagnostic cost is trivial next to the value of knowing
                    // why the board just froze, even for programs that never opted into --gc-log.
                    // A no-op if the program never called Serial.begin(), same as every other Serial
                    // call site here.
                    Serial.print("[juno-gc] OOM: need ");
                    Serial.print(padded);
                    Serial.print(" bytes, arena_used=");
                    Serial.print(juno_arena_used);
                    Serial.print("/");
                    Serial.println(sizeof(juno_arena));
                    juno_panic();
                  }
                  uint8_t* bytes = static_cast<uint8_t*>(memory);
                  for (uint32_t index = 0; index < padded; index++) bytes[index] = 0;
                  return memory;
                }

                ${JUNO_LED_MATRIX_FUNCTIONS}extern "C" void juno_serial_begin(int32_t baud) {
                  Serial.begin(static_cast<unsigned long>(baud));
                }

                extern "C" void juno_serial_print(int32_t value) {
                  Serial.print(value);
                }

                extern "C" void juno_serial_println(int32_t value) {
                  Serial.println(value);
                }

                extern "C" void juno_serial_print_long(int64_t value) {
                  Serial.print(static_cast<long long>(value));
                }

                extern "C" void juno_serial_println_long(int64_t value) {
                  Serial.println(static_cast<long long>(value));
                }

                extern "C" JUNO_ASM_ABI void juno_serial_print_float(float value) {
                  Serial.print(static_cast<double>(value));
                }

                extern "C" JUNO_ASM_ABI void juno_serial_println_float(float value) {
                  Serial.println(static_cast<double>(value));
                }

                extern "C" JUNO_ASM_ABI void juno_serial_print_double(double value) {
                  Serial.print(value);
                }

                extern "C" JUNO_ASM_ABI void juno_serial_println_double(double value) {
                  Serial.println(value);
                }

                // A runtime String (e.g. Throwable.getMessage()) may be null; Java prints "null".
                extern "C" void juno_serial_print_str(const char* value) {
                  Serial.print(value != nullptr ? value : "null");
                }

                extern "C" void juno_serial_println_str(const char* value) {
                  Serial.println(value != nullptr ? value : "null");
                }
                """.replace("${JUNO_YIELD_FUNCTION}", yieldFunction)
                .replace("${JUNO_LED_MATRIX_FUNCTIONS}", ledMatrixFunctions)
                .replace("${JUNO_ARENA_CAPACITY}", Integer.toString(RuntimeLimits.ARENA_CAPACITY_BYTES))
                .replace("${JUNO_GC_STACK_SCAN}", gcStackScan)
                .replace("${JUNO_GC_THREAD_DECLARATION}", gcThreadDeclaration)
                .replace("${JUNO_GC_LOG_BEFORE}", gcLogBefore)
                .replace("${JUNO_GC_LOG_AFTER}", gcLogAfter)
                .replace("${JUNO_WATCHDOG_REFRESH}", watchdogRefresh)
                .replace("${JUNO_WATCHDOG_PANIC_MESSAGE}", watchdogPanicMessage)
                .replace("${JUNO_WATCHDOG_BEGIN_FUNCTION}", watchdogBeginFunction);
    }

    private String ledMatrixFunctions() {
        // The LED matrix helpers need the UNO R4's Arduino_LED_Matrix library; the linker already
        // rejects LedMatrix calls on boards without one, so they are left out there.
        return !board.supports(Capability.LED_MATRIX) ? "" : """
                static ArduinoLEDMatrix juno_led_matrix;

                extern "C" void juno_led_matrix_begin() {
                  juno_led_matrix.begin();
                }

                extern "C" void juno_led_matrix_load_frame(int32_t word0, int32_t word1, int32_t word2) {
                  const uint32_t frame[3] = {
                    static_cast<uint32_t>(word0),
                    static_cast<uint32_t>(word1),
                    static_cast<uint32_t>(word2)
                  };
                  juno_led_matrix.loadFrame(frame);
                }

                extern "C" void juno_led_matrix_clear() {
                  const uint32_t frame[3] = {0, 0, 0};
                  juno_led_matrix.loadFrame(frame);
                }

                """;
    }

    private void appendHelpers(StringBuilder shim) {
        if (usesAny(ShimFeature.RUNTIME_STRINGS, ShimFeature.STRING_BUILDER)) {
            shim.append(ShimLibraries.runtimeStringHelpers());
        }
        if (uses(ShimFeature.STRING_BUILDER)) {
            shim.append(ShimLibraries.stringBuilderHelpers());
        }
        if (uses(ShimFeature.MOUSE)) {
            shim.append(ShimLibraries.mouseHelpers());
        }
        if (uses(ShimFeature.SERVO)) {
            shim.append(ShimLibraries.servoHelpers());
        }
        if (uses(ShimFeature.LEGO_POWERED_UP)) {
            shim.append(ShimLibraries.legoPoweredUpHelpers());
        }
        if (uses(ShimFeature.MEMORY)) {
            shim.append(ShimLibraries.memoryHelpers());
        }
        if (uses(ShimFeature.RANDOM)) {
            shim.append(ShimLibraries.randomHelpers());
        }
        if (uses(ShimFeature.WIFI)) {
            shim.append(core.wifiHelpers());
        }
        if (uses(ShimFeature.UDP)) {
            shim.append(NetworkShimLibraries.udpHelpers(core.udpDeclaration()));
        }
        if (uses(ShimFeature.SD)) {
            shim.append(ShimLibraries.sdHelpers());
        }
        if (uses(ShimFeature.LONG)) {
            shim.append(ShimLibraries.longHelpers());
        }
        if (uses(ShimFeature.FLOAT)) {
            shim.append(ShimLibraries.floatHelpers());
        }
        if (uses(ShimFeature.DOUBLE)) {
            shim.append(ShimLibraries.doubleHelpers());
        }
        if (!usedMath.isEmpty()) {
            shim.append(MathRuntime.helpers(usedMath));
        }
        if (uses(ShimFeature.EXCEPTIONS)) {
            shim.append(ShimLibraries.exceptionHelpers(throwableClasses));
        }
        if (uses(ShimFeature.JSON)) {
            shim.append(NetworkShimLibraries.jsonHelpers());
        }
        if (uses(ShimFeature.JSON_STRING_VALUE)) {
            shim.append(NetworkShimLibraries.jsonStringValueHelpers());
        }
        if (usesAny(ShimFeature.HTTPS, ShimFeature.SMTP_TLS, ShimFeature.POP3)) {
            shim.append(core.httpsHelpers());
        }
        if (usesAny(ShimFeature.HTTP, ShimFeature.HTTPS)) {
            shim.append(NetworkShimLibraries.httpHelpers(features, core.httpsClientDeclaration()));
        }
        if (uses(ShimFeature.HTTP_SERVER)) {
            shim.append(NetworkShimLibraries.httpServerHelpers(core.httpServerTransport()));
        }
        if (usesAny(ShimFeature.SMTP, ShimFeature.SMTP_TLS, ShimFeature.POP3)) {
            shim.append(NetworkShimLibraries.emailHelpers(features, core.httpsClientDeclaration()));
        }
        appendConcurrencyHelpers(shim);
    }

    /** Scoped-value bindings, then the thread scheduler that swaps them (it refers to the binding stack). */
    private void appendConcurrencyHelpers(StringBuilder shim) {
        if (uses(ShimFeature.SCOPED_VALUES)) {
            shim.append(ScopedValueRuntime.bindings(uses(ShimFeature.THREAD_ENTRY),
                    uses(ShimFeature.SCOPED_CALL_ENTRY),
                    throwableClasses.indexOf("java/util/NoSuchElementException")));
        }
        if (uses(ShimFeature.THREADS)) {
            shim.append(core.threadPort());
            shim.append(ThreadRuntime.scheduler(core.delayMillisFunction(), uses(ShimFeature.EXCEPTIONS),
                    uses(ShimFeature.THREAD_ENTRY), uses(ShimFeature.TASK_CALLABLE_ENTRY),
                    uses(ShimFeature.STRUCTURED_TASKS), uses(ShimFeature.SCOPED_VALUES),
                    throwableClasses.indexOf("java/util/concurrent/StructuredTaskScope$FailedException"),
                    throwableClasses.indexOf("java/lang/IllegalStateException")));
        } else if (uses(ShimFeature.THREAD_BASICS)) {
            shim.append(ThreadRuntime.basics(core.delayMillisFunction()));
        }
    }
}
