package io.github.jabrena.juno.api.tft;

import static org.assertj.core.api.Assertions.assertThat;

import io.github.jabrena.juno.CompilationResult;
import io.github.jabrena.juno.JunoCompiler;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import org.testcontainers.containers.Container.ExecResult;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.images.builder.ImageFromDockerfile;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.utility.DockerImageName;
import org.testcontainers.utility.MountableFile;

/**
 * Compiles every TFT game the way {@code juno:verify} does — Juno generates the sketch, then
 * {@code arduino-cli compile --fqbn arduino:renesas_uno:unor4wifi} builds and links it with the real
 * UNO R4 core — inside a Docker container, so no local Arduino installation is needed.
 *
 * <p>Opt-in, as it needs Docker and downloads the core on first use:
 * {@code ./mvnw install -DskipTests} once, then {@code ./mvnw -f juno-examples/pom.xml -Parduino-cli test}.
 * The image is built from {@code src/test/docker/arduino-cli/Dockerfile}; to use a prebuilt image
 * instead, pass {@code -Djuno.arduinoCliImage=<image>}. Skipped when Docker is not available.
 */
@Tag("arduino-cli")
@Testcontainers(disabledWithoutDocker = true)
class ArduinoCliCompileTest {
    private static final String FQBN = "arduino:renesas_uno:unor4wifi";
    private static final Path BASEDIR = Path.of(System.getProperty("basedir", ".")).toAbsolutePath().normalize();
    private static final Pattern FLASH = Pattern.compile("Sketch uses (\\d+) bytes \\((\\d+)%\\)");
    private static final Pattern RAM = Pattern.compile("Global variables use (\\d+) bytes \\((\\d+)%\\)");

    @Container
    private static final GenericContainer<?> ARDUINO_CLI = container().withCommand("sleep", "infinity");

    static Stream<String> games() throws IOException {
        try (Stream<Path> sources = Files.list(BASEDIR.resolve("src/main/java/io/github/jabrena/juno/api/tft"))) {
            return sources.map(path -> path.getFileName().toString())
                    .filter(name -> name.endsWith(".java") && !name.equals("TftTouchShield.java")
                            && !name.equals("package-info.java"))
                    .map(name -> name.substring(0, name.length() - ".java".length()))
                    .sorted()
                    .toList()
                    .stream();
        }
    }

    @ParameterizedTest(name = "{0}")
    @MethodSource("games")
    void compilesAndLinksWithArduinoCli(String game) throws Exception {
        Path sketch = generateSketch(game);
        String target = "/sketches/" + sketch.getFileName();
        ARDUINO_CLI.copyFileToContainer(MountableFile.forHostPath(sketch), target);

        ExecResult result = ARDUINO_CLI.execInContainer("arduino-cli", "compile", "--fqbn", FQBN, target);

        String output = result.getStdout() + result.getStderr();
        assertThat(result.getExitCode()).as("arduino-cli compile %s:%n%s", game, output).isZero();
        Matcher flash = FLASH.matcher(output);
        Matcher ram = RAM.matcher(output);
        assertThat(flash.find()).as("flash usage reported:%n%s", output).isTrue();
        assertThat(ram.find()).as("RAM usage reported:%n%s", output).isTrue();
        assertThat(Integer.parseInt(flash.group(2))).as("flash used by %s", game).isLessThan(100);
        assertThat(Integer.parseInt(ram.group(2))).as("RAM used by %s", game).isLessThan(100);
        System.out.println(game + ": " + flash.group() + ", " + ram.group());
    }

    /** Runs Juno on the game, writing the same sketch directory {@code juno:compile} does. */
    private static Path generateSketch(String game) throws IOException {
        String sketchName = game + "Asm";
        Path directory = BASEDIR.resolve("target/arduino-cli-sketches").resolve(sketchName);
        Files.createDirectories(directory);
        CompilationResult result = new JunoCompiler().compileTo(junoClasspath(),
                "io.github.jabrena.juno.api.tft." + game, directory.resolve(game + ".S"),
                directory.resolve(game + "Shim.cpp"), false);
        // The .ino wrapper juno-maven-plugin writes (AbstractJunoMojo#writeAsmWrapper).
        String wrapper = """
                // Generated by Juno. Do not edit.
                extern "C" void %s();

                void setup() {
                  %s();
                }

                void loop() {
                }
                """.formatted(result.entryPointSymbol(), result.entryPointSymbol());
        Files.writeString(directory.resolve(sketchName + ".ino"), wrapper, StandardCharsets.UTF_8);
        return directory;
    }

    /**
     * Juno's closed-world classpath, as {@code juno:compile} builds it from the compile classpath:
     * the examples plus the {@code juno} artifact. Test classes (whose hardware doubles would replace
     * the real native API) and test-only libraries are left out.
     */
    private static List<Path> junoClasspath() {
        List<Path> entries = new ArrayList<>();
        entries.add(BASEDIR.resolve("target/classes"));
        String classpath = System.getProperty("surefire.test.class.path", System.getProperty("java.class.path"));
        for (String entry : classpath.split(File.pathSeparator)) {
            Path path = Path.of(entry).toAbsolutePath().normalize();
            String name = path.getFileName() == null ? "" : path.getFileName().toString();
            boolean reactorJuno = path.endsWith(Path.of("juno", "target", "classes"));
            boolean installedJuno = name.startsWith("juno-") && name.endsWith(".jar")
                    && !name.startsWith("juno-maven-plugin") && !name.startsWith("juno-examples");
            if (reactorJuno || installedJuno) {
                entries.add(path);
            }
        }
        return entries;
    }

    private static GenericContainer<?> container() {
        String prebuilt = System.getProperty("juno.arduinoCliImage", "");
        if (!prebuilt.isBlank()) {
            return new GenericContainer<>(DockerImageName.parse(prebuilt));
        }
        return new GenericContainer<>(new ImageFromDockerfile("juno-arduino-cli", false)
                .withFileFromPath(".", BASEDIR.resolve("src/test/docker/arduino-cli")));
    }
}
