package io.github.jabrena.juno.intrinsic;

import io.github.jabrena.juno.classfile.MethodRef;

import java.util.Map;
import java.util.Optional;

/** The single place that resolves a Java {@link MethodRef} to the {@link Intrinsic} it implements. */
public final class IntrinsicRegistry {
    private static final Map<MethodRef, Intrinsic> METHODS = Map.ofEntries(
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/Gpio", "pinMode", "(II)V"),
                    Intrinsic.GPIO_PIN_MODE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/Gpio", "digitalWrite", "(IZ)V"),
                    Intrinsic.GPIO_DIGITAL_WRITE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/Gpio", "digitalRead", "(I)Z"),
                    Intrinsic.GPIO_DIGITAL_READ),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/Gpio", "analogRead", "(I)I"),
                    Intrinsic.GPIO_ANALOG_READ),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/Gpio", "analogWrite", "(II)V"),
                    Intrinsic.GPIO_ANALOG_WRITE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/Gpio", "toggle", "(I)V"),
                    Intrinsic.GPIO_TOGGLE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/Delay", "millis", "(I)V"),
                    Intrinsic.DELAY_MILLIS),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/Delay", "micros", "(I)V"),
                    Intrinsic.DELAY_MICROS),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/Clock", "millis", "()I"),
                    Intrinsic.CLOCK_MILLIS),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/Clock", "micros", "()I"),
                    Intrinsic.CLOCK_MICROS),
            Map.entry(new MethodRef("java/lang/String", "valueOf", "(I)Ljava/lang/String;"),
                    Intrinsic.STRING_VALUE_OF_INT),
            Map.entry(new MethodRef("java/lang/String", "valueOf", "(D)Ljava/lang/String;"),
                    Intrinsic.STRING_VALUE_OF_DOUBLE),
            Map.entry(new MethodRef("java/lang/String", "length", "()I"),
                    Intrinsic.STRING_LENGTH),
            Map.entry(new MethodRef("java/lang/String", "charAt", "(I)C"),
                    Intrinsic.STRING_CHAR_AT),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/DigitalOutput", "of",
                    "(I)Lio/github/jabrena/juno/api/io/DigitalOutput;"), Intrinsic.DIGITAL_OUTPUT_OF),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/DigitalOutput", "high", "()V"),
                    Intrinsic.DIGITAL_OUTPUT_HIGH),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/DigitalOutput", "low", "()V"),
                    Intrinsic.DIGITAL_OUTPUT_LOW),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/DigitalOutput", "toggle", "()V"),
                    Intrinsic.DIGITAL_OUTPUT_TOGGLE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/DigitalOutput", "isHigh", "()Z"),
                    Intrinsic.DIGITAL_OUTPUT_IS_HIGH),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/led/LedMatrix", "begin", "()V"),
                    Intrinsic.LED_MATRIX_BEGIN),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/led/LedMatrix", "loadFrame", "(III)V"),
                    Intrinsic.LED_MATRIX_LOAD_FRAME),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/led/LedMatrix", "clear", "()V"),
                    Intrinsic.LED_MATRIX_CLEAR),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/usb/Serial", "begin", "(I)V"),
                    Intrinsic.SERIAL_BEGIN),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/usb/Serial", "print", "(I)V"),
                    Intrinsic.SERIAL_PRINT),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/usb/Serial", "println", "(I)V"),
                    Intrinsic.SERIAL_PRINTLN),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/usb/Serial", "print", "(Ljava/lang/String;)V"),
                    Intrinsic.SERIAL_PRINT_STRING),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/usb/Serial", "println", "(Ljava/lang/String;)V"),
                    Intrinsic.SERIAL_PRINTLN_STRING),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/hid/Mouse", "begin", "()V"),
                    Intrinsic.MOUSE_BEGIN),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/hid/Mouse", "move", "(II)V"),
                    Intrinsic.MOUSE_MOVE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/Wifi", "begin",
                    "(Ljava/lang/String;Ljava/lang/String;)V"), Intrinsic.WIFI_BEGIN),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/Wifi", "status", "()I"),
                    Intrinsic.WIFI_STATUS),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/HttpClient", "get",
                    "(Ljava/lang/String;ILjava/lang/String;[BI)I"), Intrinsic.HTTP_GET),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/HttpClient", "post",
                    "(Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;[BI)I"), Intrinsic.HTTP_POST),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/HttpClient", "delete",
                    "(Ljava/lang/String;ILjava/lang/String;[BI)I"), Intrinsic.HTTP_DELETE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/HttpClient", "patch",
                    "(Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;[BI)I"), Intrinsic.HTTP_PATCH),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/HttpClient", "query",
                    "(Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;[BI)I"), Intrinsic.HTTP_QUERY),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/HttpsClient", "get",
                    "(Ljava/lang/String;ILjava/lang/String;[BI)I"), Intrinsic.HTTPS_GET),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/HttpsClient", "post",
                    "(Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;[BI)I"), Intrinsic.HTTPS_POST),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/HttpsClient", "delete",
                    "(Ljava/lang/String;ILjava/lang/String;[BI)I"), Intrinsic.HTTPS_DELETE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/HttpsClient", "patch",
                    "(Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;[BI)I"), Intrinsic.HTTPS_PATCH),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/HttpsClient", "query",
                    "(Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;[BI)I"), Intrinsic.HTTPS_QUERY),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/Json", "type",
                    "([BILjava/lang/String;)I"), Intrinsic.JSON_TYPE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/Json", "getInt",
                    "([BILjava/lang/String;)I"), Intrinsic.JSON_GET_INT),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/Json", "getLong",
                    "([BILjava/lang/String;)J"), Intrinsic.JSON_GET_LONG),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/Json", "getDouble",
                    "([BILjava/lang/String;)D"), Intrinsic.JSON_GET_DOUBLE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/Json", "getBool",
                    "([BILjava/lang/String;)Z"), Intrinsic.JSON_GET_BOOL),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/Json", "getString",
                    "([BILjava/lang/String;[BI)I"), Intrinsic.JSON_GET_STRING),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/Json", "getString",
                    "([BILjava/lang/String;)Ljava/lang/String;"), Intrinsic.JSON_GET_STRING_VALUE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/Json", "arraySize",
                    "([BILjava/lang/String;)I"), Intrinsic.JSON_ARRAY_SIZE));

    private IntrinsicRegistry() {
    }

    public static Optional<Intrinsic> resolve(MethodRef method) {
        return Optional.ofNullable(METHODS.get(method));
    }

    public static boolean isIntrinsic(MethodRef method) {
        return METHODS.containsKey(method);
    }
}
