package io.github.jabrena.juno.intrinsic;

import io.github.jabrena.juno.classfile.MethodRef;

import java.util.Map;
import java.util.Optional;
import java.util.Set;

/** The single place that resolves a Java {@link MethodRef} to the {@link Intrinsic} it implements. */
public final class IntrinsicRegistry {
    /**
     * (intrinsic, declared-parameter-index) pairs exempt from the default rule that every
     * intrinsic {@code String} parameter must be a compile-time literal. {@link
     * io.github.jabrena.juno.api.io.net.http.HttpServer#respond(int, String, String)}'s {@code body}
     * (parameter index 2, after {@code status} and {@code contentType}), for example, works
     * identically whether the argument is a literal (a {@code .asciz} address) or a
     * runtime value (a pooled {@code String}'s address) — both are plain null-terminated {@code
     * const char*} to the generated {@code juno_http_server_respond} shim. {@code Wifi#begin}'s
     * credentials are also runtime-capable so values loaded from an SD-card {@code Properties}
     * document can be passed directly to the WiFi driver.
     */
    private static final Set<IntrinsicParameter> RUNTIME_STRING_PARAMETERS = Set.of(
            new IntrinsicParameter(Intrinsic.HTTP_SERVER_RESPOND, 2),
            new IntrinsicParameter(Intrinsic.WIFI_BEGIN, 0),
            new IntrinsicParameter(Intrinsic.WIFI_BEGIN, 1),
            new IntrinsicParameter(Intrinsic.PROPERTIES_GET, 0),
            new IntrinsicParameter(Intrinsic.PROPERTIES_GET_DEFAULT, 0),
            new IntrinsicParameter(Intrinsic.PROPERTIES_GET_DEFAULT, 1),
            new IntrinsicParameter(Intrinsic.SD_APPEND, 1));

    /**
     * Parameters that accept a runtime {@code String} but still take the literal path (a {@code .asciz}
     * address, no extra IR) when the argument is a known literal: {@code Serial.print(e.getMessage())}
     * compiles, while {@code Serial.print("text")} generates exactly what it always has.
     */
    private static final Set<IntrinsicParameter> LITERAL_WHEN_KNOWN_PARAMETERS = Set.of(
            new IntrinsicParameter(Intrinsic.SERIAL_PRINT_STRING, 0),
            new IntrinsicParameter(Intrinsic.SERIAL_PRINTLN_STRING, 0));

    private record IntrinsicParameter(Intrinsic intrinsic, int parameterIndex) {
    }

    private static final Map<MethodRef, Intrinsic> METHODS = Map.ofEntries(
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/Gpio", "pinMode", "(II)V"),
                    Intrinsic.GPIO_PIN_MODE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/Gpio", "digitalWrite", "(IZ)V"),
                    Intrinsic.GPIO_DIGITAL_WRITE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/Gpio", "digitalRead", "(I)Z"),
                    Intrinsic.GPIO_DIGITAL_READ),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/Gpio", "analogRead", "(I)I"),
                    Intrinsic.GPIO_ANALOG_READ),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/Gpio", "analogWrite", "(II)V"),
                    Intrinsic.GPIO_ANALOG_WRITE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/Gpio", "toggle", "(I)V"),
                    Intrinsic.GPIO_TOGGLE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/Gpio", "builtinLed", "()I"),
                    Intrinsic.GPIO_BUILTIN_LED),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/Delay", "millis", "(I)V"),
                    Intrinsic.DELAY_MILLIS),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/Delay", "micros", "(I)V"),
                    Intrinsic.DELAY_MICROS),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/Clock", "millis", "()I"),
                    Intrinsic.CLOCK_MILLIS),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/Clock", "micros", "()I"),
                    Intrinsic.CLOCK_MICROS),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/Random", "seed", "(I)V"),
                    Intrinsic.RANDOM_SEED),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/Random", "nextInt", "(I)I"),
                    Intrinsic.RANDOM_NEXT_BOUND),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/Random", "nextInt", "(II)I"),
                    Intrinsic.RANDOM_NEXT_RANGE),
            Map.entry(new MethodRef("java/lang/String", "valueOf", "(I)Ljava/lang/String;"),
                    Intrinsic.STRING_VALUE_OF_INT),
            Map.entry(new MethodRef("java/lang/String", "valueOf", "(D)Ljava/lang/String;"),
                    Intrinsic.STRING_VALUE_OF_DOUBLE),
            Map.entry(new MethodRef("java/lang/String", "length", "()I"),
                    Intrinsic.STRING_LENGTH),
            Map.entry(new MethodRef("java/lang/String", "charAt", "(I)C"),
                    Intrinsic.STRING_CHAR_AT),
            Map.entry(new MethodRef("java/lang/String", "equals", "(Ljava/lang/Object;)Z"),
                    Intrinsic.STRING_EQUALS),
            Map.entry(new MethodRef("java/lang/StringBuilder", "<init>", "(I)V"),
                    Intrinsic.STRING_BUILDER_NEW),
            Map.entry(new MethodRef("java/lang/StringBuilder", "append", "(C)Ljava/lang/StringBuilder;"),
                    Intrinsic.STRING_BUILDER_APPEND_CHAR),
            Map.entry(new MethodRef("java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;"),
                    Intrinsic.STRING_BUILDER_APPEND_STRING),
            Map.entry(new MethodRef("java/lang/StringBuilder", "toString", "()Ljava/lang/String;"),
                    Intrinsic.STRING_BUILDER_TO_STRING),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/DigitalOutput", "of",
                    "(I)Lio/github/jabrena/juno/api/io/DigitalOutput;"), Intrinsic.DIGITAL_OUTPUT_OF),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/DigitalOutput", "high", "()V"),
                    Intrinsic.DIGITAL_OUTPUT_HIGH),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/DigitalOutput", "low", "()V"),
                    Intrinsic.DIGITAL_OUTPUT_LOW),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/DigitalOutput", "toggle", "()V"),
                    Intrinsic.DIGITAL_OUTPUT_TOGGLE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/DigitalOutput", "isHigh", "()Z"),
                    Intrinsic.DIGITAL_OUTPUT_IS_HIGH),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/led/LedMatrix", "begin", "()V"),
                    Intrinsic.LED_MATRIX_BEGIN),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/led/LedMatrix", "loadFrame", "(III)V"),
                    Intrinsic.LED_MATRIX_LOAD_FRAME),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/led/LedMatrix", "clear", "()V"),
                    Intrinsic.LED_MATRIX_CLEAR),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/usb/Serial", "begin", "(I)V"),
                    Intrinsic.SERIAL_BEGIN),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/usb/Serial", "print", "(I)V"),
                    Intrinsic.SERIAL_PRINT),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/usb/Serial", "println", "(I)V"),
                    Intrinsic.SERIAL_PRINTLN),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/usb/Serial", "print", "(J)V"),
                    Intrinsic.SERIAL_PRINT_LONG),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/usb/Serial", "println", "(J)V"),
                    Intrinsic.SERIAL_PRINTLN_LONG),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/usb/Serial", "print", "(F)V"),
                    Intrinsic.SERIAL_PRINT_FLOAT),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/usb/Serial", "println", "(F)V"),
                    Intrinsic.SERIAL_PRINTLN_FLOAT),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/usb/Serial", "print", "(D)V"),
                    Intrinsic.SERIAL_PRINT_DOUBLE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/usb/Serial", "println", "(D)V"),
                    Intrinsic.SERIAL_PRINTLN_DOUBLE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/usb/Serial", "print", "(Ljava/lang/String;)V"),
                    Intrinsic.SERIAL_PRINT_STRING),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/usb/Serial", "println", "(Ljava/lang/String;)V"),
                    Intrinsic.SERIAL_PRINTLN_STRING),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/hid/Mouse", "begin", "()V"),
                    Intrinsic.MOUSE_BEGIN),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/hid/Mouse", "move", "(II)V"),
                    Intrinsic.MOUSE_MOVE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/motors/Servo", "of",
                    "(I)Lio/github/jabrena/juno/api/motors/Servo;"), Intrinsic.SERVO_OF),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/motors/Servo", "write", "(I)V"),
                    Intrinsic.SERVO_WRITE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/lego/PoweredUpHub", "connect", "(I)Z"),
                    Intrinsic.LEGO_HUB_CONNECT),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/lego/PoweredUpHub", "isConnected", "()Z"),
                    Intrinsic.LEGO_HUB_IS_CONNECTED),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/lego/PoweredUpHub", "hubType", "()I"),
                    Intrinsic.LEGO_HUB_TYPE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/lego/PoweredUpHub", "setMotorPower", "(II)V"),
                    Intrinsic.LEGO_HUB_SET_MOTOR_POWER),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/lego/PoweredUpHub", "brakeMotor", "(I)V"),
                    Intrinsic.LEGO_HUB_BRAKE_MOTOR),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/lego/PoweredUpHub", "setLedColor", "(I)V"),
                    Intrinsic.LEGO_HUB_SET_LED_COLOR),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/lego/PoweredUpHub", "enableSensor", "(II)V"),
                    Intrinsic.LEGO_HUB_ENABLE_SENSOR),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/lego/PoweredUpHub", "readSensor", "(I)I"),
                    Intrinsic.LEGO_HUB_READ_SENSOR),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/lego/PoweredUpHub", "disconnect", "()V"),
                    Intrinsic.LEGO_HUB_DISCONNECT),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/lego/PoweredUpHub", "switchOff", "()V"),
                    Intrinsic.LEGO_HUB_SWITCH_OFF),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/Wifi", "begin",
                    "(Ljava/lang/String;Ljava/lang/String;)V"), Intrinsic.WIFI_BEGIN),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/Wifi", "status", "()I"),
                    Intrinsic.WIFI_STATUS),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/Wifi", "localIP", "([I)V"),
                    Intrinsic.WIFI_LOCAL_IP),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/Udp", "listen", "(I)Z"),
                    Intrinsic.UDP_LISTEN),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/Udp", "send", "([II[BI)I"),
                    Intrinsic.UDP_SEND),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/Udp", "broadcast", "(I[BI)I"),
                    Intrinsic.UDP_BROADCAST),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/Udp", "receive", "([BI[I)I"),
                    Intrinsic.UDP_RECEIVE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/Udp", "stop", "()V"),
                    Intrinsic.UDP_STOP),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/storage/SdCard", "begin", "(I)Z"),
                    Intrinsic.SD_BEGIN),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/storage/SdCard", "exists",
                    "(Ljava/lang/String;)Z"), Intrinsic.SD_EXISTS),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/storage/SdCard", "open",
                    "(Ljava/lang/String;)Ljava/io/InputStream;"), Intrinsic.SD_OPEN),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/storage/SdCard", "append",
                    "(Ljava/lang/String;Ljava/lang/String;)Z"), Intrinsic.SD_APPEND),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/storage/SdCard", "remove",
                    "(Ljava/lang/String;)Z"), Intrinsic.SD_REMOVE),
            Map.entry(new MethodRef("java/io/InputStream", "available", "()I"),
                    Intrinsic.SD_FILE_AVAILABLE),
            Map.entry(new MethodRef("java/io/InputStream", "read", "()I"),
                    Intrinsic.SD_FILE_READ),
            Map.entry(new MethodRef("java/io/InputStream", "close", "()V"),
                    Intrinsic.SD_FILE_CLOSE),
            Map.entry(new MethodRef("java/util/Properties", "<init>", "()V"), Intrinsic.PROPERTIES_NEW),
            Map.entry(new MethodRef("java/util/Properties", "load", "(Ljava/io/InputStream;)V"),
                    Intrinsic.PROPERTIES_LOAD),
            Map.entry(new MethodRef("java/util/Properties", "getProperty",
                    "(Ljava/lang/String;)Ljava/lang/String;"), Intrinsic.PROPERTIES_GET),
            Map.entry(new MethodRef("java/util/Properties", "getProperty",
                    "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;"), Intrinsic.PROPERTIES_GET_DEFAULT),
            Map.entry(new MethodRef("java/util/Properties", "size", "()I"),
                    Intrinsic.PROPERTIES_SIZE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/HttpClient", "get",
                    "(Ljava/lang/String;ILjava/lang/String;[BI[BI[I)I"), Intrinsic.HTTP_GET),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/HttpClient", "post",
                    "(Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;[BI[BI[I)I"), Intrinsic.HTTP_POST),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/HttpClient", "delete",
                    "(Ljava/lang/String;ILjava/lang/String;[BI[BI[I)I"), Intrinsic.HTTP_DELETE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/HttpClient", "patch",
                    "(Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;[BI[BI[I)I"), Intrinsic.HTTP_PATCH),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/HttpClient", "query",
                    "(Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;[BI[BI[I)I"), Intrinsic.HTTP_QUERY),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/HttpsClient", "get",
                    "(Ljava/lang/String;ILjava/lang/String;[BI[BI[I)I"), Intrinsic.HTTPS_GET),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/HttpsClient", "get",
                    "(Ljava/lang/String;I[BI[BI[BI[I)I"), Intrinsic.HTTPS_GET_PATH_BUFFER),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/HttpsClient", "post",
                    "(Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;[BI[BI[I)I"), Intrinsic.HTTPS_POST),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/HttpsClient", "delete",
                    "(Ljava/lang/String;ILjava/lang/String;[BI[BI[I)I"), Intrinsic.HTTPS_DELETE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/HttpsClient", "patch",
                    "(Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;[BI[BI[I)I"), Intrinsic.HTTPS_PATCH),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/HttpsClient", "query",
                    "(Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;[BI[BI[I)I"), Intrinsic.HTTPS_QUERY),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/Json", "type",
                    "([BILjava/lang/String;)I"), Intrinsic.JSON_TYPE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/Json", "getInt",
                    "([BILjava/lang/String;)I"), Intrinsic.JSON_GET_INT),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/Json", "getLong",
                    "([BILjava/lang/String;)J"), Intrinsic.JSON_GET_LONG),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/Json", "getDouble",
                    "([BILjava/lang/String;)D"), Intrinsic.JSON_GET_DOUBLE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/Json", "getBool",
                    "([BILjava/lang/String;)Z"), Intrinsic.JSON_GET_BOOL),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/Json", "getString",
                    "([BILjava/lang/String;[BI)I"), Intrinsic.JSON_GET_STRING),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/Json", "getString",
                    "([BILjava/lang/String;)Ljava/lang/String;"), Intrinsic.JSON_GET_STRING_VALUE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/Json", "arraySize",
                    "([BILjava/lang/String;)I"), Intrinsic.JSON_ARRAY_SIZE),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/HttpServer", "begin", "(I)V"),
                    Intrinsic.HTTP_SERVER_BEGIN),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/HttpServer", "accept", "([BI)I"),
                    Intrinsic.HTTP_SERVER_ACCEPT),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/HttpServer", "method", "()Ljava/lang/String;"),
                    Intrinsic.HTTP_SERVER_METHOD),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/HttpServer", "path", "()Ljava/lang/String;"),
                    Intrinsic.HTTP_SERVER_PATH),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/HttpServer", "respond",
                    "(ILjava/lang/String;Ljava/lang/String;)V"), Intrinsic.HTTP_SERVER_RESPOND),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/http/HttpServer", "respond",
                    "(ILjava/lang/String;Ljava/lang/StringBuilder;)V"), Intrinsic.HTTP_SERVER_RESPOND_BUILDER),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/Memory", "arenaUsedBytes", "()I"),
                    Intrinsic.MEMORY_ARENA_USED),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/email/Smtp", "send",
                    "(Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;"
                            + "Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I"), Intrinsic.SMTP_SEND),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/email/Smtp", "sendTls",
                    "(Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;"
                            + "Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I"), Intrinsic.SMTP_SEND_TLS),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/email/Pop3Client", "messageCount",
                    "(Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)I"), Intrinsic.POP3_MESSAGE_COUNT),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/email/Pop3Client", "readLatest",
                    "(Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;[BI[BI[I)I"), Intrinsic.POP3_READ_LATEST),
            Map.entry(new MethodRef("io/github/jabrena/juno/api/io/net/email/Pop3Client", "readSubject",
                    "(Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;I[BI)I"), Intrinsic.POP3_READ_SUBJECT),
            Map.entry(new MethodRef("java/lang/Thread", "<init>", "(Ljava/lang/Runnable;)V"), Intrinsic.THREAD_NEW),
            Map.entry(new MethodRef("java/lang/Thread", "start", "()V"), Intrinsic.THREAD_START),
            Map.entry(new MethodRef("java/lang/Thread", "join", "()V"), Intrinsic.THREAD_JOIN),
            Map.entry(new MethodRef("java/lang/Thread", "isAlive", "()Z"), Intrinsic.THREAD_IS_ALIVE),
            Map.entry(new MethodRef("java/lang/Thread", "setDaemon", "(Z)V"), Intrinsic.THREAD_SET_DAEMON),
            Map.entry(new MethodRef("java/lang/Thread", "sleep", "(J)V"), Intrinsic.THREAD_SLEEP),
            Map.entry(new MethodRef("java/lang/Thread", "yield", "()V"), Intrinsic.THREAD_YIELD),
            Map.entry(new MethodRef("java/util/concurrent/StructuredTaskScope$ShutdownOnFailure", "<init>", "()V"),
                    Intrinsic.TASK_SCOPE_NEW_FAILURE),
            Map.entry(new MethodRef("java/util/concurrent/StructuredTaskScope$ShutdownOnSuccess", "<init>", "()V"),
                    Intrinsic.TASK_SCOPE_NEW_SUCCESS),
            Map.entry(new MethodRef("java/util/concurrent/StructuredTaskScope", "fork",
                    "(Ljava/util/concurrent/Callable;)Ljava/util/concurrent/StructuredTaskScope$Subtask;"),
                    Intrinsic.TASK_SCOPE_FORK),
            Map.entry(new MethodRef("java/util/concurrent/StructuredTaskScope$ShutdownOnFailure", "fork",
                    "(Ljava/util/concurrent/Callable;)Ljava/util/concurrent/StructuredTaskScope$Subtask;"),
                    Intrinsic.TASK_SCOPE_FORK),
            Map.entry(new MethodRef("java/util/concurrent/StructuredTaskScope$ShutdownOnSuccess", "fork",
                    "(Ljava/util/concurrent/Callable;)Ljava/util/concurrent/StructuredTaskScope$Subtask;"),
                    Intrinsic.TASK_SCOPE_FORK),
            Map.entry(new MethodRef("java/util/concurrent/StructuredTaskScope", "join",
                    "()Ljava/util/concurrent/StructuredTaskScope;"), Intrinsic.TASK_SCOPE_JOIN),
            Map.entry(new MethodRef("java/util/concurrent/StructuredTaskScope$ShutdownOnFailure", "join",
                    "()Ljava/util/concurrent/StructuredTaskScope$ShutdownOnFailure;"), Intrinsic.TASK_SCOPE_JOIN),
            Map.entry(new MethodRef("java/util/concurrent/StructuredTaskScope$ShutdownOnSuccess", "join",
                    "()Ljava/util/concurrent/StructuredTaskScope$ShutdownOnSuccess;"), Intrinsic.TASK_SCOPE_JOIN),
            Map.entry(new MethodRef("java/util/concurrent/StructuredTaskScope$ShutdownOnFailure", "throwIfFailed",
                    "()V"), Intrinsic.TASK_SCOPE_THROW_IF_FAILED),
            Map.entry(new MethodRef("java/util/concurrent/StructuredTaskScope$ShutdownOnSuccess", "result",
                    "()Ljava/lang/Object;"), Intrinsic.TASK_SCOPE_RESULT),
            Map.entry(new MethodRef("java/util/concurrent/StructuredTaskScope$Subtask", "get",
                    "()Ljava/lang/Object;"), Intrinsic.TASK_GET),
            Map.entry(new MethodRef("java/util/concurrent/StructuredTaskScope", "close", "()V"),
                    Intrinsic.TASK_SCOPE_CLOSE),
            Map.entry(new MethodRef("java/util/concurrent/StructuredTaskScope$ShutdownOnFailure", "close", "()V"),
                    Intrinsic.TASK_SCOPE_CLOSE),
            Map.entry(new MethodRef("java/util/concurrent/StructuredTaskScope$ShutdownOnSuccess", "close", "()V"),
                    Intrinsic.TASK_SCOPE_CLOSE),
            Map.entry(new MethodRef("java/util/concurrent/locks/ReentrantLock", "<init>", "()V"),
                    Intrinsic.REENTRANT_LOCK_NEW),
            Map.entry(new MethodRef("java/util/concurrent/locks/ReentrantLock", "lock", "()V"),
                    Intrinsic.REENTRANT_LOCK_LOCK),
            Map.entry(new MethodRef("java/util/concurrent/locks/ReentrantLock", "tryLock", "()Z"),
                    Intrinsic.REENTRANT_LOCK_TRY_LOCK),
            Map.entry(new MethodRef("java/util/concurrent/locks/ReentrantLock", "unlock", "()V"),
                    Intrinsic.REENTRANT_LOCK_UNLOCK),
            Map.entry(new MethodRef("java/lang/Math", "abs", "(I)I"), Intrinsic.MATH_ABS_INT),
            Map.entry(new MethodRef("java/lang/Math", "abs", "(J)J"), Intrinsic.MATH_ABS_LONG),
            Map.entry(new MethodRef("java/lang/Math", "abs", "(F)F"), Intrinsic.MATH_ABS_FLOAT),
            Map.entry(new MethodRef("java/lang/Math", "abs", "(D)D"), Intrinsic.MATH_ABS_DOUBLE),
            Map.entry(new MethodRef("java/lang/Math", "min", "(II)I"), Intrinsic.MATH_MIN_INT),
            Map.entry(new MethodRef("java/lang/Math", "min", "(JJ)J"), Intrinsic.MATH_MIN_LONG),
            Map.entry(new MethodRef("java/lang/Math", "min", "(FF)F"), Intrinsic.MATH_MIN_FLOAT),
            Map.entry(new MethodRef("java/lang/Math", "min", "(DD)D"), Intrinsic.MATH_MIN_DOUBLE),
            Map.entry(new MethodRef("java/lang/Math", "max", "(II)I"), Intrinsic.MATH_MAX_INT),
            Map.entry(new MethodRef("java/lang/Math", "max", "(JJ)J"), Intrinsic.MATH_MAX_LONG),
            Map.entry(new MethodRef("java/lang/Math", "max", "(FF)F"), Intrinsic.MATH_MAX_FLOAT),
            Map.entry(new MethodRef("java/lang/Math", "max", "(DD)D"), Intrinsic.MATH_MAX_DOUBLE),
            Map.entry(new MethodRef("java/lang/Math", "clamp", "(JII)I"), Intrinsic.MATH_CLAMP_INT),
            Map.entry(new MethodRef("java/lang/Math", "clamp", "(JJJ)J"), Intrinsic.MATH_CLAMP_LONG),
            Map.entry(new MethodRef("java/lang/Math", "clamp", "(FFF)F"), Intrinsic.MATH_CLAMP_FLOAT),
            Map.entry(new MethodRef("java/lang/Math", "clamp", "(DDD)D"), Intrinsic.MATH_CLAMP_DOUBLE),
            Map.entry(new MethodRef("java/lang/Math", "floorDiv", "(II)I"), Intrinsic.MATH_FLOOR_DIV_INT),
            Map.entry(new MethodRef("java/lang/Math", "floorDiv", "(JJ)J"), Intrinsic.MATH_FLOOR_DIV_LONG),
            Map.entry(new MethodRef("java/lang/Math", "floorDiv", "(JI)J"), Intrinsic.MATH_FLOOR_DIV_LONG_INT),
            Map.entry(new MethodRef("java/lang/Math", "floorMod", "(II)I"), Intrinsic.MATH_FLOOR_MOD_INT),
            Map.entry(new MethodRef("java/lang/Math", "floorMod", "(JJ)J"), Intrinsic.MATH_FLOOR_MOD_LONG),
            Map.entry(new MethodRef("java/lang/Math", "floorMod", "(JI)I"), Intrinsic.MATH_FLOOR_MOD_LONG_INT),
            Map.entry(new MethodRef("java/lang/Math", "signum", "(F)F"), Intrinsic.MATH_SIGNUM_FLOAT),
            Map.entry(new MethodRef("java/lang/Math", "signum", "(D)D"), Intrinsic.MATH_SIGNUM_DOUBLE),
            Map.entry(new MethodRef("java/lang/Math", "round", "(F)I"), Intrinsic.MATH_ROUND_FLOAT),
            Map.entry(new MethodRef("java/lang/Math", "round", "(D)J"), Intrinsic.MATH_ROUND_DOUBLE),
            Map.entry(new MethodRef("java/lang/Math", "floor", "(D)D"), Intrinsic.MATH_FLOOR),
            Map.entry(new MethodRef("java/lang/Math", "ceil", "(D)D"), Intrinsic.MATH_CEIL),
            Map.entry(new MethodRef("java/lang/Math", "sqrt", "(D)D"), Intrinsic.MATH_SQRT),
            Map.entry(new MethodRef("java/lang/Math", "cbrt", "(D)D"), Intrinsic.MATH_CBRT),
            Map.entry(new MethodRef("java/lang/Math", "pow", "(DD)D"), Intrinsic.MATH_POW),
            Map.entry(new MethodRef("java/lang/Math", "hypot", "(DD)D"), Intrinsic.MATH_HYPOT),
            Map.entry(new MethodRef("java/lang/Math", "exp", "(D)D"), Intrinsic.MATH_EXP),
            Map.entry(new MethodRef("java/lang/Math", "log", "(D)D"), Intrinsic.MATH_LOG),
            Map.entry(new MethodRef("java/lang/Math", "log10", "(D)D"), Intrinsic.MATH_LOG10),
            Map.entry(new MethodRef("java/lang/Math", "sin", "(D)D"), Intrinsic.MATH_SIN),
            Map.entry(new MethodRef("java/lang/Math", "cos", "(D)D"), Intrinsic.MATH_COS),
            Map.entry(new MethodRef("java/lang/Math", "tan", "(D)D"), Intrinsic.MATH_TAN),
            Map.entry(new MethodRef("java/lang/Math", "asin", "(D)D"), Intrinsic.MATH_ASIN),
            Map.entry(new MethodRef("java/lang/Math", "acos", "(D)D"), Intrinsic.MATH_ACOS),
            Map.entry(new MethodRef("java/lang/Math", "atan", "(D)D"), Intrinsic.MATH_ATAN),
            Map.entry(new MethodRef("java/lang/Math", "atan2", "(DD)D"), Intrinsic.MATH_ATAN2),
            Map.entry(new MethodRef("java/lang/Math", "toRadians", "(D)D"), Intrinsic.MATH_TO_RADIANS),
            Map.entry(new MethodRef("java/lang/Math", "toDegrees", "(D)D"), Intrinsic.MATH_TO_DEGREES));

    private IntrinsicRegistry() {
    }

    public static Optional<Intrinsic> resolve(MethodRef method) {
        return Optional.ofNullable(METHODS.get(method));
    }

    public static boolean isIntrinsic(MethodRef method) {
        return METHODS.containsKey(method);
    }

    /** Whether {@code intrinsic}'s {@code String} parameter at {@code parameterIndex} must be a compile-time literal. */
    public static boolean requiresLiteralStringArgument(Intrinsic intrinsic, int parameterIndex) {
        IntrinsicParameter parameter = new IntrinsicParameter(intrinsic, parameterIndex);
        return !RUNTIME_STRING_PARAMETERS.contains(parameter) && !LITERAL_WHEN_KNOWN_PARAMETERS.contains(parameter);
    }

    /** Whether a known-literal argument for this runtime-capable parameter should still be passed as a literal. */
    public static boolean prefersLiteralStringArgument(Intrinsic intrinsic, int parameterIndex) {
        return LITERAL_WHEN_KNOWN_PARAMETERS.contains(new IntrinsicParameter(intrinsic, parameterIndex));
    }
}
