package io.github.jabrena.juno.maven;

import io.github.jabrena.juno.CompileException;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Path;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class JunoBackendTest {
    @TempDir
    Path temporaryDirectory;

    @Test
    void usesAsmByDefault() {
        assertThat(JunoBackend.parse(null)).isEqualTo(JunoBackend.ASM);
        assertThat(JunoBackend.parse(" ")).isEqualTo(JunoBackend.ASM);
    }

    @Test
    void acceptsAsmAndCppCaseInsensitively() {
        assertThat(JunoBackend.parse("asm")).isEqualTo(JunoBackend.ASM);
        assertThat(JunoBackend.parse("CPP")).isEqualTo(JunoBackend.CPP);
    }

    @Test
    void rejectsUnknownBackend() {
        assertThatThrownBy(() -> JunoBackend.parse("llvm"))
                .isInstanceOf(CompileException.class)
                .hasMessageContaining("expected asm or cpp");
    }

    @Test
    void writesArduinoWrapperForAssemblyEntryPoint() throws Exception {
        Path wrapper = temporaryDirectory.resolve("BlinkAsm/BlinkAsm.ino");

        AbstractJunoMojo.writeAsmWrapper(wrapper, "juno_Blink_asm");

        assertThat(wrapper).hasContent("""
                // Generated by Juno. Do not edit.
                extern "C" void juno_Blink_asm();

                void setup() {
                  juno_Blink_asm();
                }

                void loop() {
                }
                """);
    }
}
