package io.github.jabrena.juno;

import io.github.jabrena.juno.analysis.BasicBlock;
import io.github.jabrena.juno.analysis.RuntimeRiskReportFormatter;
import io.github.jabrena.juno.board.Board;
import io.github.jabrena.juno.ir.IrBasicBlock;
import io.github.jabrena.juno.ir.IrInstruction;
import io.github.jabrena.juno.ir.IrMethod;
import io.github.jabrena.juno.ir.IrProgram;
import io.github.jabrena.juno.linker.LinkedMethod;
import io.github.jabrena.juno.linker.Program;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;

public final class Main {
    private static final String VERSION = "0.1.0-SNAPSHOT";

    private Main() {
    }

    public static void main(String[] args) {
        try {
            run(args);
        } catch (CompileException exception) {
            System.err.println("juno: " + exception.getMessage());
            System.exit(2);
        }
    }

    static void run(String[] args) {
        if (args.length == 0 || Arrays.asList(args).contains("--help") || Arrays.asList(args).contains("-h")) {
            System.out.print(usage());
            return;
        }
        if (args.length == 1 && args[0].equals("--version")) {
            System.out.println("Juno " + VERSION);
            return;
        }
        if (args[0].equals("compile")) {
            runCompile(args);
        } else if (args[0].equals("inspect")) {
            runInspect(args);
        } else {
            throw new CompileException("Unknown command '" + args[0] + "'. Run with --help for usage.");
        }
    }

    private static void runCompile(String[] args) {
        String mainClass = null;
        String classPathValue = "target/classes";
        Path output = null;
        boolean gcLog = false;
        String requestedBoardId = null;
        for (int index = 1; index < args.length; index++) {
            String option = args[index];
            if (option.equals("--main")) {
                mainClass = value(args, ++index, option);
            } else if (option.equals("--classpath") || option.equals("-cp")) {
                classPathValue = value(args, ++index, option);
            } else if (option.equals("--output") || option.equals("-o")) {
                output = Path.of(value(args, ++index, option));
            } else if (option.equals("--gc-log")) {
                gcLog = true;
            } else if (option.equals("--board")) {
                requestedBoardId = value(args, ++index, option);
            } else {
                throw new CompileException("Unknown option '" + option + "'");
            }
        }
        if (mainClass == null) {
            throw new CompileException("Missing required option --main");
        }
        if (output == null) {
            String simpleName = mainClass.substring(mainClass.lastIndexOf('.') + 1);
            output = Path.of("build", "juno", simpleName, simpleName + ".S");
        }
        List<Path> classPath = parseClassPath(classPathValue);

        String baseName = baseName(output);
        Path shimOutput = output.resolveSibling(baseName + "Shim.cpp");
        Path wrapperOutput = output.resolveSibling(baseName + ".ino");
        CompilationResult result = new JunoCompiler().compileTo(classPath, mainClass, output, shimOutput, gcLog,
                Optional.ofNullable(requestedBoardId));
        writeWrapper(wrapperOutput, result.entryPointSymbol());
        Board board = result.report().board();
        System.out.println("Generated " + output + ", " + shimOutput + ", and " + wrapperOutput
                + " for " + board.displayName() + " (fqbn " + board.fqbn() + ")");
        System.out.println();
        RuntimeRiskReportFormatter.format(result.report().runtimeRisks()).forEach(System.out::println);
    }

    private static String baseName(Path path) {
        String fileName = path.getFileName().toString();
        int dot = fileName.lastIndexOf('.');
        return dot < 0 ? fileName : fileName.substring(0, dot);
    }

    private static void writeWrapper(Path output, String entryPointSymbol) {
        String wrapper = """
                // Generated by Juno. Do not edit.
                extern "C" void %s();

                void setup() {
                  %s();
                }

                void loop() {
                }
                """.formatted(entryPointSymbol, entryPointSymbol);
        try {
            Files.createDirectories(output.toAbsolutePath().getParent());
            Files.writeString(output, wrapper, StandardCharsets.UTF_8);
        } catch (IOException exception) {
            throw new CompileException("Cannot write generated sketch wrapper to " + output, exception);
        }
    }

    private static void runInspect(String[] args) {
        String mainClass = null;
        String classPathValue = "target/classes";
        boolean showIr = false;
        boolean showCfg = false;
        String board = null;
        for (int index = 1; index < args.length; index++) {
            String option = args[index];
            if (option.equals("--main")) {
                mainClass = value(args, ++index, option);
            } else if (option.equals("--classpath") || option.equals("-cp")) {
                classPathValue = value(args, ++index, option);
            } else if (option.equals("--ir")) {
                showIr = true;
            } else if (option.equals("--cfg")) {
                showCfg = true;
            } else if (option.equals("--board")) {
                board = value(args, ++index, option);
            } else {
                throw new CompileException("Unknown option '" + option + "'");
            }
        }
        if (mainClass == null) {
            throw new CompileException("Missing required option --main");
        }
        List<Path> classPath = parseClassPath(classPathValue);

        CompilationPipeline pipeline = new CompilationPipeline();
        Program program = pipeline.link(classPath, mainClass, Optional.ofNullable(board));
        IrProgram optimized = pipeline.optimize(pipeline.lower(program));
        CompilationReport report = CompilationReport.from(program, optimized);

        System.out.println("Entry point: " + report.entryPoint().displayName());
        System.out.println("Board: " + report.board().displayName() + " (fqbn " + report.board().fqbn() + ")");
        System.out.println("Reachable methods: " + report.reachableMethods());
        System.out.println("IR basic blocks: " + report.irBlocks());
        System.out.println("Intrinsics used: " + (report.intrinsics().isEmpty() ? "(none)" : report.intrinsics()));

        if (showCfg) {
            System.out.println();
            System.out.println("Control flow graphs:");
            for (LinkedMethod linked : program.methods()) {
                System.out.println("  " + linked.method().reference().displayName());
                for (BasicBlock block : linked.controlFlowGraph().blocks()) {
                    System.out.println("    block " + block.start() + " -> " + block.terminator());
                }
            }
        }
        if (showIr) {
            System.out.println();
            System.out.println("Juno IR:");
            for (IrMethod method : optimized.methods()) {
                System.out.println("  " + method.reference().displayName());
                for (IrBasicBlock block : method.blocks()) {
                    System.out.println("    block " + block.start() + ":");
                    for (IrInstruction instruction : block.instructions()) {
                        System.out.println("      " + instruction);
                    }
                    System.out.println("      " + block.terminator());
                }
            }
        }
    }

    private static List<Path> parseClassPath(String classPathValue) {
        List<Path> classPath = new ArrayList<>();
        for (String entry : classPathValue.split(java.util.regex.Pattern.quote(File.pathSeparator))) {
            if (!entry.isBlank()) {
                classPath.add(Path.of(entry));
            }
        }
        if (classPath.isEmpty()) {
            throw new CompileException("Classpath is empty");
        }
        return classPath;
    }

    private static String value(String[] args, int index, String option) {
        if (index >= args.length) {
            throw new CompileException("Missing value for " + option);
        }
        return args[index];
    }

    private static String usage() {
        return """
                Juno - Java AOT compiler for Arduino UNO R4

                Usage:
                  java -jar juno.jar compile --main <class> [options]
                  java -jar juno.jar inspect --main <class> [options]

                compile options:
                  --classpath, -cp <paths>  Class directories or JARs (default: target/classes)
                  --output, -o <file>       Generated .S file (default: build/juno/<Main>/<Main>.S)
                  --board <id>              Target board (arduino-uno-r4-wifi, arduino-uno-q); required only when
                                            @Board declares more than one board
                  --gc-log                  Have the generated garbage collector print one Serial
                                            line per collection (arena bytes used before/after),
                                            visible via juno:monitor. Off by default: costs no
                                            extra flash/RAM/time when omitted.
                  Also emits <Main>Shim.cpp and the matching <Main>.ino wrapper alongside it.
                  Runtime-risk resource estimates and structured findings are printed automatically
                  afterward (also true of juno-maven-plugin's compile/verify/upload goals).

                The target board is read from the entry-point class's @Board annotation
                (io.github.jabrena.juno.annotations.Board); a class with no @Board annotation targets the
                UNO R4 WiFi by default. @Board may declare more than one board (e.g.
                @Board({ArduinoUnoR4WiFi.class, ArduinoUnoQ.class})), in which case --board picks which one
                this build compiles for.

                inspect options:
                  --classpath, -cp <paths>  Class directories or JARs (default: target/classes)
                  --board <id>              Target board (arduino-uno-r4-wifi, arduino-uno-q); required only when
                                            @Board declares more than one board
                  --ir                      Print the lowered/optimized Juno IR per reachable method
                  --cfg                     Print each reachable method's basic-block control flow graph

                Global options:
                  --help, -h                Show this help
                  --version                 Show the version
                """;
    }
}
