package io.github.jabrena.juno.maven;

import io.github.jabrena.juno.AsmCompilationResult;
import io.github.jabrena.juno.CompilationReport;
import io.github.jabrena.juno.CompilationResult;
import io.github.jabrena.juno.CompileException;
import io.github.jabrena.juno.JunoCompiler;
import org.apache.maven.plugins.annotations.Parameter;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

abstract class AbstractJunoMojo extends AbstractArduinoMojo {
    /** Fully qualified Java entry-point class. */
    @Parameter(property = "juno.main", required = true)
    private String mainClass;

    /** Maven compile classpath used as Juno's closed-world classpath. */
    @Parameter(defaultValue = "${project.compileClasspathElements}", readonly = true, required = true)
    private List<String> classpathElements;

    /** Directory under which one Arduino sketch directory is created per entry point. */
    @Parameter(property = "juno.outputDirectory", defaultValue = "${project.build.directory}/juno", required = true)
    private File outputDirectory;

    /** Code-generation backend: {@code asm} (default) or {@code cpp}. */
    @Parameter(property = "juno.backend", defaultValue = "asm", required = true)
    private String backend;

    final CompiledSketch compileSketch() {
        if (mainClass == null || mainClass.isBlank()) {
            throw new ArduinoCliException("Missing required Juno entry point; configure <mainClass> or -Djuno.main=<class>");
        }
        if (classpathElements == null || classpathElements.isEmpty()) {
            throw new ArduinoCliException("Maven compile classpath is empty");
        }

        String trimmedMain = mainClass.trim();
        String simpleName = trimmedMain.substring(trimmedMain.lastIndexOf('.') + 1);
        List<Path> classpath = classpathElements.stream().map(Path::of).toList();

        return switch (JunoBackend.parse(backend)) {
            case ASM -> compileAsmSketch(classpath, trimmedMain, simpleName);
            case CPP -> compileCppSketch(classpath, trimmedMain, simpleName);
        };
    }

    private CompiledSketch compileCppSketch(List<Path> classpath, String mainClass, String simpleName) {
        Path sketchDirectory = outputDirectory().resolve(simpleName);
        Path sketch = sketchDirectory.resolve(simpleName + ".ino");

        CompilationResult result = new JunoCompiler().compileTo(classpath, mainClass, sketch);
        String targetFqbn = targetFqbn(result.report().board().fqbn());
        warnForFqbnOverride(targetFqbn, result.report());
        getLog().info("Generated " + sketch + " for " + result.report().board().displayName()
                + " with the C++ backend (fqbn " + targetFqbn + ")");
        return new CompiledSketch(sketchDirectory, targetFqbn, JunoBackend.CPP);
    }

    private CompiledSketch compileAsmSketch(List<Path> classpath, String mainClass, String simpleName) {
        String sketchName = simpleName + "Asm";
        Path sketchDirectory = outputDirectory().resolve(sketchName);
        Path assembly = sketchDirectory.resolve(simpleName + ".S");
        Path shim = sketchDirectory.resolve(simpleName + "Shim.cpp");
        Path wrapper = sketchDirectory.resolve(sketchName + ".ino");

        AsmCompilationResult result = new JunoCompiler().compileAsmTo(classpath, mainClass, assembly, shim);
        writeAsmWrapper(wrapper, result.entryPointSymbol());
        String targetFqbn = targetFqbn(result.report().board().fqbn());
        warnForFqbnOverride(targetFqbn, result.report());
        getLog().info("Generated " + assembly + ", " + shim + ", and " + wrapper + " for "
                + result.report().board().displayName() + " with the experimental ASM backend (fqbn "
                + targetFqbn + ")");
        return new CompiledSketch(sketchDirectory, targetFqbn, JunoBackend.ASM);
    }

    private Path outputDirectory() {
        return outputDirectory.toPath().toAbsolutePath().normalize();
    }

    private void warnForFqbnOverride(String targetFqbn, CompilationReport report) {
        if (!targetFqbn.equals(report.board().fqbn())) {
            getLog().warn("Configured FQBN " + targetFqbn + " overrides @Board target "
                    + report.board().fqbn());
        }
    }

    static void writeAsmWrapper(Path output, String entryPointSymbol) {
        String wrapper = """
                // Generated by Juno. Do not edit.
                extern "C" void %s();

                void setup() {
                  %s();
                }

                void loop() {
                }
                """.formatted(entryPointSymbol, entryPointSymbol);
        try {
            Files.createDirectories(output.toAbsolutePath().getParent());
            Files.writeString(output, wrapper, StandardCharsets.UTF_8);
        } catch (IOException exception) {
            throw new CompileException("Cannot write generated ASM sketch wrapper to " + output, exception);
        }
    }

    final void verifySketch(ArduinoCli cli, CompiledSketch sketch) {
        getLog().info("Compiling " + sketch.backend() + " Arduino sketch with arduino-cli");
        cli.compile(sketch.fqbn(), sketch.directory());
    }

    record CompiledSketch(Path directory, String fqbn, JunoBackend backend) {
    }
}
