package io.github.jabrena.juno.maven;

import io.github.jabrena.juno.CompilationReport;
import io.github.jabrena.juno.CompilationResult;
import io.github.jabrena.juno.CompileException;
import io.github.jabrena.juno.JunoCompiler;
import io.github.jabrena.juno.analysis.RuntimeRiskReportFormatter;
import org.apache.maven.plugins.annotations.Parameter;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Optional;

abstract class AbstractJunoMojo extends AbstractArduinoMojo {
    /** Fully qualified Java entry-point class. */
    @Parameter(property = "juno.main", required = true)
    private String mainClass;

    /** Maven compile classpath used as Juno's closed-world classpath. */
    @Parameter(defaultValue = "${project.compileClasspathElements}", readonly = true, required = true)
    private List<String> classpathElements;

    /** Directory under which one Arduino sketch directory is created per entry point. */
    @Parameter(property = "juno.outputDirectory", defaultValue = "${project.build.directory}/juno", required = true)
    private File outputDirectory;

    /**
     * Have the generated garbage collector print one Serial line per collection (arena bytes used
     * before/after), visible via {@code juno:monitor}. Off by default: costs no extra
     * flash/RAM/time when disabled, since the print statements aren't emitted at all.
     */
    @Parameter(property = "juno.gcLog", defaultValue = "false")
    private boolean gcLog;

    /**
     * Target board (e.g. {@code arduino-uno-r4-wifi}, {@code arduino-uno-q}), required only when the entry point's
     * {@code @Board} annotation declares more than one board; the compiler fails rather than picking
     * one silently. Ignored when the entry point declares a single board.
     */
    @Parameter(property = "juno.board")
    private String board;

    final CompiledSketch compileSketch() {
        if (mainClass == null || mainClass.isBlank()) {
            throw new ArduinoCliException("Missing required Juno entry point; configure <mainClass> or -Djuno.main=<class>");
        }
        if (classpathElements == null || classpathElements.isEmpty()) {
            throw new ArduinoCliException("Maven compile classpath is empty");
        }

        String trimmedMain = mainClass.trim();
        String simpleName = trimmedMain.substring(trimmedMain.lastIndexOf('.') + 1);
        List<Path> classpath = classpathElements.stream().map(Path::of).toList();

        return compileAsmSketch(classpath, trimmedMain, simpleName);
    }

    private CompiledSketch compileAsmSketch(List<Path> classpath, String mainClass, String simpleName) {
        String sketchName = simpleName + "Asm";
        Path sketchDirectory = outputDirectory().resolve(sketchName);
        Path assembly = sketchDirectory.resolve(simpleName + ".S");
        Path shim = sketchDirectory.resolve(simpleName + "Shim.cpp");
        Path wrapper = sketchDirectory.resolve(sketchName + ".ino");

        Optional<String> requestedBoard = board == null || board.isBlank() ? Optional.empty() : Optional.of(board.trim());
        CompilationResult result = new JunoCompiler().compileTo(classpath, mainClass, assembly, shim, gcLog,
                requestedBoard);
        writeAsmWrapper(wrapper, result.entryPointSymbol());
        String targetFqbn = targetFqbn(result.report().board().fqbn());
        warnForFqbnOverride(targetFqbn, result.report());
        getLog().info("Generated " + assembly + ", " + shim + ", and " + wrapper + " for "
                + result.report().board().displayName() + " with the ASM backend (fqbn "
                + targetFqbn + ")");
        RuntimeRiskReportFormatter.format(result.report().runtimeRisks()).forEach(getLog()::info);
        return new CompiledSketch(sketchDirectory, targetFqbn);
    }

    private Path outputDirectory() {
        return outputDirectory.toPath().toAbsolutePath().normalize();
    }

    private void warnForFqbnOverride(String targetFqbn, CompilationReport report) {
        if (!targetFqbn.equals(report.board().fqbn())) {
            getLog().warn("Configured FQBN " + targetFqbn + " overrides @Board target "
                    + report.board().fqbn());
        }
    }

    static void writeAsmWrapper(Path output, String entryPointSymbol) {
        String wrapper = """
                // Generated by Juno. Do not edit.
                extern "C" void %s();

                void setup() {
                  %s();
                }

                void loop() {
                }
                """.formatted(entryPointSymbol, entryPointSymbol);
        try {
            Files.createDirectories(output.toAbsolutePath().getParent());
            Files.writeString(output, wrapper, StandardCharsets.UTF_8);
        } catch (IOException exception) {
            throw new CompileException("Cannot write generated ASM sketch wrapper to " + output, exception);
        }
    }

    final void verifySketch(ArduinoCli cli, CompiledSketch sketch) {
        getLog().info("Compiling ASM Arduino sketch with arduino-cli");
        cli.compile(sketch.fqbn(), sketch.directory());
    }

    record CompiledSketch(Path directory, String fqbn) {
    }
}
